// Code generated by `go run ./tools/gen-ts-types`. DO NOT EDIT.
//
// Structural mirror of the sqlc-generated + repo wire-facing Go structs
// (issue #365) — see backend/tools/gen-ts-types/main.go for what it does and
// deliberately does not do (enum unions, the full internal/db package).
// Regenerate with `make backend-gen-ts-types`; CI
// (`make backend-gen-ts-types-check`) fails if this file is stale.

export type Asset = {
  id: string;
  household_id: string;
  display_name: string;
  description: string | null;
  subtype: string;
  ownership_type: string;
  sole_owner_user_id: string | null;
  native_currency: string;
  status: string;
  terminated_at: string | null;
  termination_note: string | null;
  created_by: string | null;
  created_at: string;
  updated_by: string | null;
  updated_at: string;
  tag_id: string | null;
};

export type AssetSnapshot = {
  id: string;
  asset_id: string;
  year_month: string;
  amount: string;
  currency: string;
  as_of_date: string | null;
  description: string | null;
  created_by: string | null;
  created_at: string;
  updated_by: string | null;
  updated_at: string;
};

export type Tag = {
  id: string;
  household_id: string;
  name: string;
  color: string;
  created_by: string | null;
  created_at: string;
  updated_by: string | null;
  updated_at: string;
  deleted_at: string | null;
};

export type FxRate = {
  id: string;
  household_id: string;
  year_month: string;
  currency: string;
  rate: string;
  created_by: string | null;
  created_at: string;
  updated_by: string | null;
  updated_at: string;
};

export type Income = {
  id: string;
  household_id: string;
  date: string;
  amount: string;
  currency: string;
  category: string;
  description: string | null;
  ownership_type: string;
  sole_owner_user_id: string | null;
  created_by: string | null;
  created_at: string;
  updated_by: string | null;
  updated_at: string;
  regularity: string;
};

export type Investment = {
  id: string;
  household_id: string;
  display_name: string;
  description: string | null;
  subtype: string;
  ownership_type: string;
  sole_owner_user_id: string | null;
  native_currency: string;
  status: string;
  terminated_at: string | null;
  termination_note: string | null;
  created_by: string | null;
  created_at: string;
  updated_by: string | null;
  updated_at: string;
  risk_profile: string;
  rolled_from_investment_id: string | null;
  tag_id: string | null;
};

export type InvestmentSnapshot = {
  id: string;
  investment_id: string;
  year_month: string;
  amount: string;
  currency: string;
  quantity: string | null;
  price_per_unit: string | null;
  accrued_interest: string | null;
  as_of_date: string | null;
  description: string | null;
  created_by: string | null;
  created_at: string;
  updated_by: string | null;
  updated_at: string;
};

export type InvestmentTransaction = {
  id: string;
  investment_id: string;
  transaction_type: string;
  transaction_date: string;
  currency: string;
  description: string | null;
  amount: string | null;
  quantity: string | null;
  price_per_unit: string | null;
  principal_amount: string | null;
  interest_amount: string | null;
  principal_disposition: string | null;
  interest_disposition: string | null;
  created_by: string | null;
  created_at: string;
  updated_by: string | null;
  updated_at: string;
};

export type Liability = {
  id: string;
  household_id: string;
  display_name: string;
  description: string | null;
  subtype: string;
  ownership_type: string;
  sole_owner_user_id: string | null;
  native_currency: string;
  status: string;
  terminated_at: string | null;
  termination_note: string | null;
  counterparty_name: string;
  principal: string | null;
  interest_rate: string | null;
  term_months: number | null;
  start_date: string | null;
  maturity_date: string | null;
  created_by: string | null;
  created_at: string;
  updated_by: string | null;
  updated_at: string;
  tag_id: string | null;
};

export type LiabilitySnapshot = {
  id: string;
  liability_id: string;
  year_month: string;
  amount: string;
  currency: string;
  as_of_date: string | null;
  description: string | null;
  created_by: string | null;
  created_at: string;
  updated_by: string | null;
  updated_at: string;
};

export type Receivable = {
  id: string;
  household_id: string;
  display_name: string;
  description: string | null;
  ownership_type: string;
  sole_owner_user_id: string | null;
  native_currency: string;
  status: string;
  terminated_at: string | null;
  termination_note: string | null;
  counterparty_name: string;
  due_date: string | null;
  created_by: string | null;
  created_at: string;
  updated_by: string | null;
  updated_at: string;
  tag_id: string | null;
};

export type ReceivableSnapshot = {
  id: string;
  receivable_id: string;
  year_month: string;
  amount: string;
  currency: string;
  as_of_date: string | null;
  description: string | null;
  created_by: string | null;
  created_at: string;
  updated_by: string | null;
  updated_at: string;
};

export type BankAccountDetails = {
  asset_id: string;
  bank_name: string;
  account_number: string;
  account_type: string;
};

export type PropertyDetails = {
  asset_id: string;
  property_type: string;
  address: string | null;
  acquisition_date: string | null;
  acquisition_cost: string | null;
  annual_appreciation_rate: string | null;
};

export type VehicleDetails = {
  asset_id: string;
  vehicle_type: string;
  make: string | null;
  model: string | null;
  year: number | null;
  plate_number: string | null;
  annual_depreciation_rate: string | null;
};

export type StockDetails = {
  investment_id: string;
  ticker: string;
  exchange: string;
};

export type MutualFundDetails = {
  investment_id: string;
  fund_code: string;
  fund_manager: string | null;
  fund_type: string;
};

export type GoldDetails = {
  investment_id: string;
  form: string;
  purity: string;
};

export type BondDetails = {
  investment_id: string;
  bond_type: string;
  issuer: string;
  coupon_rate: string;
  coupon_frequency: string;
  maturity_date: string;
  series_code: string | null;
  coupon_disposition: string;
};

export type TimeDepositDetails = {
  investment_id: string;
  bank_name: string;
  principal: string;
  interest_rate: string;
  term_months: number;
  placement_date: string;
  maturity_date: string;
  rollover_policy: string;
};

export type RolloverRef = {
  id: string;
  display_name: string;
};

