// Command gen-routes generates docs/api-routes.md — a flat inventory of every
// HTTP route the backend serves. It is the source of the `make api-routes`
// target (issue #370): the doc is regenerated from the real router, so it can
// never drift from the code the way a hand-maintained list would.
//
// Rather than parse the source, it builds the actual chi router the server
// mounts and walks it with chi.Walk — the same route table that answers real
// requests, so what you read is ground truth. Handlers are constructed with a
// nil pool (their constructors only stash the dependency; no query runs at wire
// time) and both identity providers are enabled so every conditional route
// appears. Google's OIDC discovery is served from an in-process httptest server
// so the generator stays fully offline.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"

	"github.com/kerti/balances-v2/backend/internal/assets"
	"github.com/kerti/balances-v2/backend/internal/auth"
	"github.com/kerti/balances-v2/backend/internal/config"
	"github.com/kerti/balances-v2/backend/internal/db"
	"github.com/kerti/balances-v2/backend/internal/email"
	"github.com/kerti/balances-v2/backend/internal/fxrates"
	"github.com/kerti/balances-v2/backend/internal/httpserver"
	"github.com/kerti/balances-v2/backend/internal/income"
	"github.com/kerti/balances-v2/backend/internal/investments"
	"github.com/kerti/balances-v2/backend/internal/liabilities"
	"github.com/kerti/balances-v2/backend/internal/receivables"
	"github.com/kerti/balances-v2/backend/internal/repo"
	"github.com/kerti/balances-v2/backend/internal/reports"
	"github.com/kerti/balances-v2/backend/internal/tags"
)

// outPath is written relative to the backend module root (where `go run` starts).
const outPath = "../docs/api-routes.md"

func main() {
	check := flag.Bool("check", false, "verify docs/api-routes.md is up to date without rewriting it (CI gate)")
	flag.Parse()
	if err := run(*check); err != nil {
		fmt.Fprintln(os.Stderr, "gen-routes:", err)
		os.Exit(1)
	}
}

func run(check bool) error {
	router, err := buildRouter()
	if err != nil {
		return err
	}

	type route struct{ method, pattern string }
	var routes []route
	walk := func(method string, pattern string, _ http.Handler, _ ...func(http.Handler) http.Handler) error {
		// chi records HEAD alongside every GET and injects OPTIONS; neither is
		// part of the app's contract, so drop them from the inventory.
		if method == http.MethodHead || method == http.MethodOptions {
			return nil
		}
		routes = append(routes, route{method: method, pattern: pattern})
		return nil
	}
	if err := chi.Walk(router, walk); err != nil {
		return fmt.Errorf("walking router: %w", err)
	}

	sort.Slice(routes, func(i, j int) bool {
		if routes[i].pattern != routes[j].pattern {
			return routes[i].pattern < routes[j].pattern
		}
		return methodRank(routes[i].method) < methodRank(routes[j].method)
	})

	var b strings.Builder
	b.WriteString("<!-- Generated by `make api-routes` (backend/tools/gen-routes). Do not edit by hand. -->\n\n")
	b.WriteString("# API route inventory\n\n")
	b.WriteString("Every HTTP route the backend serves, walked from the live chi router so it ")
	b.WriteString("cannot drift from the code. Regenerate with `make api-routes` after changing any ")
	b.WriteString("handler's `Mount`. The generator enables both identity providers, so provider-")
	b.WriteString("gated routes (`AUTH_GOOGLE_ENABLED` / `AUTH_LOCAL_ENABLED`, ADR-0039) appear here ")
	b.WriteString("even when a given deployment mounts only one.\n\n")
	b.WriteString("Response envelope and error shapes are the ADR-0027 `httperr` contract; auth and ")
	b.WriteString("session semantics are ADR-0038/0039. See [architecture.md](architecture.md) for ")
	b.WriteString("the request flow these routes sit in.\n\n")
	fmt.Fprintf(&b, "%d routes.\n\n", len(routes))
	b.WriteString("| Method | Path |\n")
	b.WriteString("| ------ | ---- |\n")
	for _, r := range routes {
		fmt.Fprintf(&b, "| %s | `%s` |\n", r.method, r.pattern)
	}

	generated := []byte(b.String())

	if check {
		current, err := os.ReadFile(outPath)
		if err != nil {
			return fmt.Errorf("reading %s: %w", outPath, err)
		}
		if string(current) != string(generated) {
			return fmt.Errorf("%s is stale — run `make api-routes` and commit the result", outPath)
		}
		fmt.Printf("%s is up to date (%d routes)\n", outPath, len(routes))
		return nil
	}

	if err := os.WriteFile(outPath, generated, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", outPath, err)
	}
	fmt.Printf("wrote %s (%d routes)\n", outPath, len(routes))
	return nil
}

func methodRank(m string) int {
	switch m {
	case http.MethodGet:
		return 0
	case http.MethodPost:
		return 1
	case http.MethodPut:
		return 2
	case http.MethodPatch:
		return 3
	case http.MethodDelete:
		return 4
	default:
		return 5
	}
}

// buildRouter wires the real server with a nil DB pool and both identity
// providers enabled, then returns its chi router for walking.
func buildRouter() (chi.Router, error) {
	ctx := context.Background()

	// In-process OIDC discovery document so enabling Google needs no network.
	oidcSrv := newDiscoveryServer()
	defer oidcSrv.Close()

	authH, err := auth.New(ctx, db.New(nil), auth.Config{
		GoogleEnabled: true,
		LocalEnabled:  true,
		EmailEnabled:  true,
		Google: auth.GoogleConfig{
			ClientID:     "gen-routes",
			ClientSecret: "gen-routes",
			RedirectURL:  "http://localhost/api/auth/google/callback",
			IssuerURL:    oidcSrv.URL,
		},
		SessionTTL:  time.Hour,
		FrontendURL: "http://localhost",
		BackendURL:  "http://localhost",
		Mailer:      email.NewNoopMailer(),
	})
	if err != nil {
		return nil, fmt.Errorf("building auth handlers: %w", err)
	}

	cfg := &config.Config{
		BackendURL:       "http://localhost",
		AuthLocalEnabled: true,
	}

	srv := httpserver.New(
		nil, // pool: constructors only stash it; no query runs during wiring
		cfg,
		authH,
		assets.New(repo.NewAssetRepo(nil)),
		liabilities.New(repo.NewLiabilityRepo(nil)),
		receivables.New(repo.NewReceivableRepo(nil)),
		investments.New(repo.NewInvestmentRepo(nil)),
		income.New(repo.NewIncomeRepo(nil)),
		reports.New(repo.NewMonthlyReportRepo(nil)),
		fxrates.New(repo.NewFxRateRepo(nil)),
		tags.New(repo.NewTagRepo(nil)),
	)

	router, ok := srv.Handler().(chi.Router)
	if !ok {
		return nil, fmt.Errorf("server handler is %T, not chi.Router", srv.Handler())
	}
	return router, nil
}

// newDiscoveryServer serves a minimal OIDC discovery document so
// oidc.NewProvider succeeds offline. The verifier's lazy JWKS fetch never fires
// here — we only build the router, never verify a token.
func newDiscoveryServer() *httptest.Server {
	mux := http.NewServeMux()
	var issuer string
	srv := httptest.NewServer(mux)
	issuer = srv.URL
	mux.HandleFunc("/.well-known/openid-configuration", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{
			"issuer":                 issuer,
			"authorization_endpoint": issuer + "/authorize",
			"token_endpoint":         issuer + "/token",
			"jwks_uri":               issuer + "/keys",
		})
	})
	return srv
}
