// Stands in for `virtual:pwa-register/react` under vitest (aliased in
// vitest.config.ts). The real module is generated by vite-plugin-pwa during a
// build, and jsdom has no service worker to register. The default is the
// quiet case — no update waiting — so every test that renders a layout sees no
// banner; UpdateBanner.test.tsx overrides it with vi.mock.
export function useRegisterSW() {
  return {
    needRefresh: [false, () => {}] as [boolean, (v: boolean) => void],
    offlineReady: [false, () => {}] as [boolean, (v: boolean) => void],
    updateServiceWorker: async () => {},
  };
}
