#!/usr/bin/env bash
# Regenerate THIRD-PARTY-NOTICES — the aggregated third-party license and
# copyright texts for everything that ships in a Balances release artifact:
# the GHCR container image and the single-page-app bundle it serves. See
# issue #345 (finding CF-02): MIT/BSD/ISC/Apache-2.0/OFL notice-preservation
# obligations apply to those artifacts, and this file is how we satisfy them.
#
# Sources, in the order they appear in the output:
#   1. Fonts    — the curated OFL texts in frontend/licenses/. The IBM Plex
#                 Sans wordmark ships outlined as SVG (no font dependency) and
#                 is invisible to the dependency scanners, so it must be listed
#                 here explicitly; Geist ships as woff2 and IS an npm dep, but
#                 we keep both fonts together in one section for clarity.
#   2. Backend  — go-licenses over ./cmd/balances (the module graph actually
#                 linked into the server binary), full license text per module.
#   3. Frontend — generate-license-file over the production npm dependency
#                 closure (what Vite bundles into the SPA), full text per pkg.
#
# The output is deterministic so `make licenses-check` can regenerate-and-diff
# it the way api-routes / gen-ts-types do. Run `make licenses` after any
# dependency change and commit the result; CI (and `make check`) will fail if
# the committed file is stale.
#
# Usage: scripts/gen-third-party-notices.sh [output-path]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/THIRD-PARTY-NOTICES}"

# Pinned so the output is reproducible across machines and CI.
GO_LICENSES_VERSION=v1.6.0
GLF_VERSION=3.8.1
# Our own module prefix — internal packages carry no third-party license.
SELF_MODULE=github.com/kerti/balances-v2

SEP="--------------------------------------------------------------------------------"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

emit() {
  echo "Third-Party Notices"
  echo "==================="
  echo
  echo "Balances (see LICENSE) bundles third-party software in its release"
  echo "artifacts — the container image and the single-page-app bundle it serves."
  echo "The notices below reproduce those components' license and copyright texts"
  echo "to satisfy their attribution requirements."
  echo
  echo "GENERATED by scripts/gen-third-party-notices.sh — do not edit by hand."
  echo "Regenerate with 'make licenses' after any dependency change."
  echo
  echo "$SEP"
  echo "FONTS"
  echo "$SEP"
  echo
  for f in "$ROOT"/frontend/licenses/*-OFL.txt; do
    echo ">>> $(basename "$f")"
    echo
    cat "$f"
    echo
    echo "$SEP"
  done
  echo
  echo "$SEP"
  echo "BACKEND — Go modules linked into the server binary"
  echo "$SEP"
  echo

  # CSV (module,url,license) for the license-type label; save tree for the
  # full text. Both walk the local module cache — no network once cached.
  ( cd "$ROOT/backend" && go run github.com/google/go-licenses@"$GO_LICENSES_VERSION" \
      report ./cmd/balances --ignore "$SELF_MODULE" ) >"$tmp/go.csv" 2>/dev/null
  ( cd "$ROOT/backend" && go run github.com/google/go-licenses@"$GO_LICENSES_VERSION" \
      save ./cmd/balances --save_path="$tmp/golic" --ignore "$SELF_MODULE" --force ) 2>/dev/null

  ( cd "$tmp/golic" && find . -type f | LC_ALL=C sort ) | while read -r rel; do
    rel="${rel#./}"
    module="$(dirname "$rel")"
    fname="$(basename "$rel")"
    lic="$(awk -F, -v m="$module" '$1==m{print $3; exit}' "$tmp/go.csv")"
    echo ">>> ${module}${lic:+  (${lic})}${fname:+  [${fname}]}"
    echo
    cat "$tmp/golic/$rel"
    echo
    echo "$SEP"
  done
  echo
  echo "$SEP"
  echo "FRONTEND — npm packages bundled into the SPA (production dependencies)"
  echo "$SEP"
  echo

  ( cd "$ROOT/frontend" && npx --yes generate-license-file@"$GLF_VERSION" \
      --input package.json --output "$tmp/fe.txt" --overwrite ) >/dev/null 2>&1
  cat "$tmp/fe.txt"
}

emit >"$OUT"
echo "wrote $OUT"
