// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    household_id, display_name, description, subtype,
    ownership_type, sole_owner_user_id, native_currency,
    created_by, updated_by, entry_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $8, $9
)
RETURNING id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, created_by, created_at, updated_by, updated_at, deleted_at, tag_id, entry_type
`

type CreateAssetParams struct {
	HouseholdID     uuid.UUID  `json:"household_id"`
	DisplayName     string     `json:"display_name"`
	Description     *string    `json:"description"`
	Subtype         string     `json:"subtype"`
	OwnershipType   string     `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID `json:"sole_owner_user_id"`
	NativeCurrency  string     `json:"native_currency"`
	CreatedBy       *uuid.UUID `json:"created_by"`
	EntryType       string     `json:"entry_type"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.HouseholdID,
		arg.DisplayName,
		arg.Description,
		arg.Subtype,
		arg.OwnershipType,
		arg.SoleOwnerUserID,
		arg.NativeCurrency,
		arg.CreatedBy,
		arg.EntryType,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Description,
		&i.Subtype,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.NativeCurrency,
		&i.Status,
		&i.TerminatedAt,
		&i.TerminationNote,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TagID,
		&i.EntryType,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, created_by, created_at, updated_by, updated_at, deleted_at, tag_id, entry_type
FROM assets
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetAssetByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetAssetByID(ctx context.Context, arg GetAssetByIDParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, arg.ID, arg.HouseholdID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Description,
		&i.Subtype,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.NativeCurrency,
		&i.Status,
		&i.TerminatedAt,
		&i.TerminationNote,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TagID,
		&i.EntryType,
	)
	return i, err
}

const listAssetsByHousehold = `-- name: ListAssetsByHousehold :many
SELECT id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, created_by, created_at, updated_by, updated_at, deleted_at, tag_id, entry_type
FROM assets
WHERE household_id = $1
  AND ($2::text IS NULL OR subtype = $2::text)
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListAssetsByHouseholdParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	Subtype     *string   `json:"subtype"`
}

func (q *Queries) ListAssetsByHousehold(ctx context.Context, arg ListAssetsByHouseholdParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByHousehold, arg.HouseholdID, arg.Subtype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.DisplayName,
			&i.Description,
			&i.Subtype,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
			&i.NativeCurrency,
			&i.Status,
			&i.TerminatedAt,
			&i.TerminationNote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TagID,
			&i.EntryType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAsset = `-- name: SoftDeleteAsset :execrows
UPDATE assets
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type SoftDeleteAssetParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteAsset(ctx context.Context, arg SoftDeleteAssetParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAsset, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets
SET display_name       = $3,
    description        = $4,
    ownership_type     = $5,
    sole_owner_user_id = $6,
    updated_by         = $7,
    -- entry_type is editable after the fact on purpose (ADR-0053 §3): with no
    -- engine-side advisory for a mis-declared birth, flipping it here is the
    -- only remedy — including for one inherited from a restore or an import.
    -- COALESCE rather than a plain assignment because omitting it must mean
    -- "leave the declaration alone", never "reset it to acquired" — silently
    -- undoing a newly_tracked declaration is the exact residual ADR-0053 warns
    -- restore and import against.
    entry_type         = COALESCE($8::text, entry_type),
    updated_at         = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, created_by, created_at, updated_by, updated_at, deleted_at, tag_id, entry_type
`

type UpdateAssetParams struct {
	ID              uuid.UUID  `json:"id"`
	HouseholdID     uuid.UUID  `json:"household_id"`
	DisplayName     string     `json:"display_name"`
	Description     *string    `json:"description"`
	OwnershipType   string     `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID `json:"sole_owner_user_id"`
	UpdatedBy       *uuid.UUID `json:"updated_by"`
	EntryType       *string    `json:"entry_type"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.ID,
		arg.HouseholdID,
		arg.DisplayName,
		arg.Description,
		arg.OwnershipType,
		arg.SoleOwnerUserID,
		arg.UpdatedBy,
		arg.EntryType,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Description,
		&i.Subtype,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.NativeCurrency,
		&i.Status,
		&i.TerminatedAt,
		&i.TerminationNote,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TagID,
		&i.EntryType,
	)
	return i, err
}

const updateAssetLifecycle = `-- name: UpdateAssetLifecycle :one
UPDATE assets
SET status           = $3,
    terminated_at    = $4,
    termination_note = $5,
    updated_by       = $6,
    updated_at       = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, created_by, created_at, updated_by, updated_at, deleted_at, tag_id, entry_type
`

type UpdateAssetLifecycleParams struct {
	ID              uuid.UUID  `json:"id"`
	HouseholdID     uuid.UUID  `json:"household_id"`
	Status          string     `json:"status"`
	TerminatedAt    *time.Time `json:"terminated_at"`
	TerminationNote *string    `json:"termination_note"`
	UpdatedBy       *uuid.UUID `json:"updated_by"`
}

func (q *Queries) UpdateAssetLifecycle(ctx context.Context, arg UpdateAssetLifecycleParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAssetLifecycle,
		arg.ID,
		arg.HouseholdID,
		arg.Status,
		arg.TerminatedAt,
		arg.TerminationNote,
		arg.UpdatedBy,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Description,
		&i.Subtype,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.NativeCurrency,
		&i.Status,
		&i.TerminatedAt,
		&i.TerminationNote,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TagID,
		&i.EntryType,
	)
	return i, err
}
