// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset_snapshots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createAssetSnapshot = `-- name: CreateAssetSnapshot :one

WITH owned_asset AS (
    SELECT a.id AS aid
    FROM assets a
    WHERE a.id = $1 AND a.household_id = $8::uuid AND a.deleted_at IS NULL
)
INSERT INTO asset_snapshots (
    asset_id, year_month, amount, currency, as_of_date, description,
    created_by, updated_by
)
SELECT owned_asset.aid, $2, $3, $4, $5, $6, $7, $7
FROM owned_asset
RETURNING id, asset_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateAssetSnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	YearMonth   time.Time       `json:"year_month"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	HouseholdID uuid.UUID       `json:"household_id"`
}

// All snapshot queries verify the parent asset belongs to the requesting
// Household. This is belt + suspenders on top of the application-layer
// tenancy middleware: even if a handler forgets to filter, SQL will not
// expose or mutate snapshots from another Household.
func (q *Queries) CreateAssetSnapshot(ctx context.Context, arg CreateAssetSnapshotParams) (AssetSnapshot, error) {
	row := q.db.QueryRow(ctx, createAssetSnapshot,
		arg.ID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i AssetSnapshot
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAssetForImport = `-- name: GetAssetForImport :one
SELECT a.display_name, a.native_currency
FROM assets a
WHERE a.id = $1 AND a.household_id = $2 AND a.deleted_at IS NULL
`

type GetAssetForImportParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

type GetAssetForImportRow struct {
	DisplayName    string `json:"display_name"`
	NativeCurrency string `json:"native_currency"`
}

// GetAssetForImport returns the display name + native currency of an owned
// asset. Doubles as the ownership/existence check for the snapshot importer:
// ErrNoRows means the asset doesn't exist in this household (or is deleted),
// which the repo maps to ErrNotFound -> 404.
func (q *Queries) GetAssetForImport(ctx context.Context, arg GetAssetForImportParams) (GetAssetForImportRow, error) {
	row := q.db.QueryRow(ctx, getAssetForImport, arg.ID, arg.HouseholdID)
	var i GetAssetForImportRow
	err := row.Scan(&i.DisplayName, &i.NativeCurrency)
	return i, err
}

const getAssetSnapshotByID = `-- name: GetAssetSnapshotByID :one
SELECT s.id, s.asset_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM asset_snapshots s
JOIN assets a ON a.id = s.asset_id
WHERE s.id = $1
  AND a.household_id = $2
  AND a.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type GetAssetSnapshotByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetAssetSnapshotByID(ctx context.Context, arg GetAssetSnapshotByIDParams) (AssetSnapshot, error) {
	row := q.db.QueryRow(ctx, getAssetSnapshotByID, arg.ID, arg.HouseholdID)
	var i AssetSnapshot
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAssetSnapshotsByAssetIDs = `-- name: ListAssetSnapshotsByAssetIDs :many
SELECT id, asset_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
FROM asset_snapshots
WHERE asset_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY asset_id, year_month
`

// Full ascending value series per asset, for the Assets Home time graphs
// (epic #204). Ascending order is what AssetTimeSeries' carry-forward sampling
// relies on; mirrors ListInvestmentSnapshotsByInvestmentIDs.
func (q *Queries) ListAssetSnapshotsByAssetIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]AssetSnapshot, error) {
	rows, err := q.db.Query(ctx, listAssetSnapshotsByAssetIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetSnapshot
	for rows.Next() {
		var i AssetSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetSnapshotsForAsset = `-- name: ListAssetSnapshotsForAsset :many
SELECT s.id, s.asset_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM asset_snapshots s
JOIN assets a ON a.id = s.asset_id
WHERE s.asset_id = $1
  AND a.household_id = $2
  AND a.deleted_at IS NULL
  AND s.deleted_at IS NULL
ORDER BY s.year_month DESC
`

type ListAssetSnapshotsForAssetParams struct {
	AssetID     uuid.UUID `json:"asset_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ListAssetSnapshotsForAsset(ctx context.Context, arg ListAssetSnapshotsForAssetParams) ([]AssetSnapshot, error) {
	rows, err := q.db.Query(ctx, listAssetSnapshotsForAsset, arg.AssetID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetSnapshot
	for rows.Next() {
		var i AssetSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleAssetIDsForMonth = `-- name: ListEligibleAssetIDsForMonth :many
SELECT id
FROM assets
WHERE household_id = $1::uuid
  AND deleted_at IS NULL
  AND (terminated_at IS NULL OR terminated_at >= $2::date)
`

type ListEligibleAssetIDsForMonthParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	YearMonth   time.Time `json:"year_month"`
}

// ListEligibleAssetIDsForMonth returns the ids of the household's assets that
// may legitimately hold a snapshot for the given target month (ADR-0046
// month-aware eligibility): owned, not deleted, and either still active or
// terminated in the target month or later. An asset terminated *before* the
// target month never appears — its forward contribution is already frozen by
// the carry-forward rule. There is deliberately no created_at guard: created_at
// is a record timestamp, not economic existence, and gating on it would block
// legitimate backfill of pre-creation months (the importer) and onboarding
// (enter last month for an account added today) — the per-position dialog has
// no such guard either.
func (q *Queries) ListEligibleAssetIDsForMonth(ctx context.Context, arg ListEligibleAssetIDsForMonthParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEligibleAssetIDsForMonth, arg.HouseholdID, arg.YearMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleAssetsForMonth = `-- name: ListEligibleAssetsForMonth :many
SELECT id, display_name, native_currency, subtype, ownership_type, sole_owner_user_id
FROM assets
WHERE household_id = $1::uuid
  AND deleted_at IS NULL
  AND (terminated_at IS NULL OR terminated_at >= $2::date)
ORDER BY subtype, display_name
`

type ListEligibleAssetsForMonthParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	YearMonth   time.Time `json:"year_month"`
}

type ListEligibleAssetsForMonthRow struct {
	ID              uuid.UUID  `json:"id"`
	DisplayName     string     `json:"display_name"`
	NativeCurrency  string     `json:"native_currency"`
	Subtype         string     `json:"subtype"`
	OwnershipType   string     `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID `json:"sole_owner_user_id"`
}

// ListEligibleAssetsForMonth is ListEligibleAssetIDsForMonth plus the display
// fields the bulk monthly-entry list needs (ADR-0046): name, native currency,
// and subtype so the entry view can group by type (bank account / property /
// vehicle). Ordered by subtype then display name so rows arrive pre-grouped —
// the subtype strings sort bank_account < property < vehicle, the order the
// entry view presents.
func (q *Queries) ListEligibleAssetsForMonth(ctx context.Context, arg ListEligibleAssetsForMonthParams) ([]ListEligibleAssetsForMonthRow, error) {
	rows, err := q.db.Query(ctx, listEligibleAssetsForMonth, arg.HouseholdID, arg.YearMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleAssetsForMonthRow
	for rows.Next() {
		var i ListEligibleAssetsForMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.NativeCurrency,
			&i.Subtype,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestSnapshotsByAssetIDs = `-- name: ListLatestSnapshotsByAssetIDs :many
SELECT DISTINCT ON (asset_id) id, asset_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
FROM asset_snapshots
WHERE asset_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY asset_id, year_month DESC
`

// Batch fetch of the most-recent snapshot per asset, for list views.
// Postgres DISTINCT ON keeps the first row per asset_id given the ORDER BY,
// which is asset_id then year_month DESC, so we get the latest valid snapshot.
func (q *Queries) ListLatestSnapshotsByAssetIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]AssetSnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestSnapshotsByAssetIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetSnapshot
	for rows.Next() {
		var i AssetSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestSnapshotsByAssetIDsAsOfMonth = `-- name: ListLatestSnapshotsByAssetIDsAsOfMonth :many
SELECT DISTINCT ON (asset_id) asset_id, amount, year_month
FROM asset_snapshots
WHERE asset_id = ANY($1::uuid[])
  AND deleted_at IS NULL
  AND year_month <= $2::date
ORDER BY asset_id, year_month DESC
`

type ListLatestSnapshotsByAssetIDsAsOfMonthParams struct {
	AssetIds  []uuid.UUID `json:"asset_ids"`
	YearMonth time.Time   `json:"year_month"`
}

type ListLatestSnapshotsByAssetIDsAsOfMonthRow struct {
	AssetID   uuid.UUID       `json:"asset_id"`
	Amount    decimal.Decimal `json:"amount"`
	YearMonth time.Time       `json:"year_month"`
}

// ListLatestSnapshotsByAssetIDsAsOfMonth returns, per asset, the most-recent
// snapshot at or before the target month — the carry-forward prefill for the
// entry list. Month-bounded so a value entered ahead of the target does not
// leak backwards as the prefill.
func (q *Queries) ListLatestSnapshotsByAssetIDsAsOfMonth(ctx context.Context, arg ListLatestSnapshotsByAssetIDsAsOfMonthParams) ([]ListLatestSnapshotsByAssetIDsAsOfMonthRow, error) {
	rows, err := q.db.Query(ctx, listLatestSnapshotsByAssetIDsAsOfMonth, arg.AssetIds, arg.YearMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestSnapshotsByAssetIDsAsOfMonthRow
	for rows.Next() {
		var i ListLatestSnapshotsByAssetIDsAsOfMonthRow
		if err := rows.Scan(&i.AssetID, &i.Amount, &i.YearMonth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAssetSnapshot = `-- name: SoftDeleteAssetSnapshot :execrows
UPDATE asset_snapshots s
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
FROM assets a
WHERE s.id = $1
  AND s.asset_id = a.id
  AND a.household_id = $2
  AND a.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type SoftDeleteAssetSnapshotParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteAssetSnapshot(ctx context.Context, arg SoftDeleteAssetSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAssetSnapshot, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAssetSnapshot = `-- name: UpdateAssetSnapshot :one
UPDATE asset_snapshots s
SET amount      = $3,
    currency    = $4,
    as_of_date  = $5,
    description = $6,
    updated_by  = $7,
    updated_at  = now()
FROM assets a
WHERE s.id = $1
  AND s.asset_id = a.id
  AND a.household_id = $2
  AND a.deleted_at IS NULL
  AND s.deleted_at IS NULL
RETURNING s.id, s.asset_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
`

type UpdateAssetSnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	HouseholdID uuid.UUID       `json:"household_id"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	UpdatedBy   *uuid.UUID      `json:"updated_by"`
}

func (q *Queries) UpdateAssetSnapshot(ctx context.Context, arg UpdateAssetSnapshotParams) (AssetSnapshot, error) {
	row := q.db.QueryRow(ctx, updateAssetSnapshot,
		arg.ID,
		arg.HouseholdID,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.UpdatedBy,
	)
	var i AssetSnapshot
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertAssetSnapshot = `-- name: UpsertAssetSnapshot :one
WITH owned_asset AS (
    SELECT a.id AS aid
    FROM assets a
    WHERE a.id = $1 AND a.household_id = $8::uuid AND a.deleted_at IS NULL
)
INSERT INTO asset_snapshots (
    asset_id, year_month, amount, currency, as_of_date, description,
    created_by, updated_by
)
SELECT owned_asset.aid, $2, $3, $4, $5, $6, $7, $7
FROM owned_asset
ON CONFLICT (asset_id, year_month) WHERE deleted_at IS NULL
DO UPDATE SET
    amount      = EXCLUDED.amount,
    currency    = EXCLUDED.currency,
    as_of_date  = EXCLUDED.as_of_date,
    description = EXCLUDED.description,
    updated_by  = EXCLUDED.updated_by,
    updated_at  = now()
RETURNING id, asset_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
`

type UpsertAssetSnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	YearMonth   time.Time       `json:"year_month"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	HouseholdID uuid.UUID       `json:"household_id"`
}

// UpsertAssetSnapshot inserts a snapshot or, when one already exists for the
// (asset_id, year_month) pair, overwrites it (last-write-wins) — the importer
// needs idempotent re-runs of a multi-year backfill. ON CONFLICT targets the
// partial unique index, so its predicate (deleted_at IS NULL) is repeated.
// created_by is only set on insert; updated_by always.
func (q *Queries) UpsertAssetSnapshot(ctx context.Context, arg UpsertAssetSnapshotParams) (AssetSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertAssetSnapshot,
		arg.ID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i AssetSnapshot
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
