// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backup.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getHouseholdForExport = `-- name: GetHouseholdForExport :one

SELECT id, display_name, reporting_currency, created_by, created_at, updated_by, updated_at, deleted_at, multi_currency_enabled FROM households WHERE id = $1
`

// Backup export reads (ADR-0036, issue #174).
//
// Every query is scoped to one Household and takes an include_deleted flag:
//
//	full fidelity  -> include_deleted = true  (carry soft-deleted rows verbatim)
//	compacted      -> include_deleted = false (live rows only)
//
// Detail tables (1:1 with their position, no own deleted_at/household_id) and
// snapshot/transaction tables are scoped by joining their parent on
// household_id; their liveness follows the parent's deleted_at too, so a
// compacted backup never carries orphaned history of a deleted position.
// Deterministic ORDER BY keeps exports stable (round-trip + test friendliness).
func (q *Queries) GetHouseholdForExport(ctx context.Context, householdID uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdForExport, householdID)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.ReportingCurrency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MultiCurrencyEnabled,
	)
	return i, err
}

const listAssetSnapshotsForExport = `-- name: ListAssetSnapshotsForExport :many

SELECT s.id, s.asset_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at FROM asset_snapshots s
JOIN assets a ON a.id = s.asset_id
WHERE a.household_id = $1
  AND ($2::bool OR (s.deleted_at IS NULL AND a.deleted_at IS NULL))
ORDER BY s.asset_id, s.year_month, s.id
`

type ListAssetSnapshotsForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

// ----- Snapshots + ledger (scoped via parent; liveness follows parent) -----
func (q *Queries) ListAssetSnapshotsForExport(ctx context.Context, arg ListAssetSnapshotsForExportParams) ([]AssetSnapshot, error) {
	rows, err := q.db.Query(ctx, listAssetSnapshotsForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetSnapshot
	for rows.Next() {
		var i AssetSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsForExport = `-- name: ListAssetsForExport :many
SELECT id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, created_by, created_at, updated_by, updated_at, deleted_at, tag_id FROM assets
WHERE household_id = $1
  AND (deleted_at IS NULL OR $2::bool)
ORDER BY created_at, id
`

type ListAssetsForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListAssetsForExport(ctx context.Context, arg ListAssetsForExportParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.DisplayName,
			&i.Description,
			&i.Subtype,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
			&i.NativeCurrency,
			&i.Status,
			&i.TerminatedAt,
			&i.TerminationNote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TagID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankAccountsForExport = `-- name: ListBankAccountsForExport :many

SELECT d.asset_id, d.bank_name, d.account_number, d.account_type FROM bank_account_details d
JOIN assets a ON a.id = d.asset_id
WHERE a.household_id = $1
  AND (a.deleted_at IS NULL OR $2::bool)
ORDER BY d.asset_id
`

type ListBankAccountsForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

// ----- Asset detail tables (scoped via assets) ----------------------------
func (q *Queries) ListBankAccountsForExport(ctx context.Context, arg ListBankAccountsForExportParams) ([]BankAccountDetail, error) {
	rows, err := q.db.Query(ctx, listBankAccountsForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccountDetail
	for rows.Next() {
		var i BankAccountDetail
		if err := rows.Scan(
			&i.AssetID,
			&i.BankName,
			&i.AccountNumber,
			&i.AccountType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBondsForExport = `-- name: ListBondsForExport :many
SELECT d.investment_id, d.bond_type, d.issuer, d.coupon_rate, d.coupon_frequency, d.maturity_date, d.series_code FROM bond_details d
JOIN investments i ON i.id = d.investment_id
WHERE i.household_id = $1
  AND (i.deleted_at IS NULL OR $2::bool)
ORDER BY d.investment_id
`

type ListBondsForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListBondsForExport(ctx context.Context, arg ListBondsForExportParams) ([]BondDetail, error) {
	rows, err := q.db.Query(ctx, listBondsForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BondDetail
	for rows.Next() {
		var i BondDetail
		if err := rows.Scan(
			&i.InvestmentID,
			&i.BondType,
			&i.Issuer,
			&i.CouponRate,
			&i.CouponFrequency,
			&i.MaturityDate,
			&i.SeriesCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFxRatesForExport = `-- name: ListFxRatesForExport :many
SELECT id, household_id, year_month, currency, rate, created_by, created_at, updated_by, updated_at, deleted_at FROM fx_rates
WHERE household_id = $1
  AND (deleted_at IS NULL OR $2::bool)
ORDER BY year_month, currency, id
`

type ListFxRatesForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListFxRatesForExport(ctx context.Context, arg ListFxRatesForExportParams) ([]FxRate, error) {
	rows, err := q.db.Query(ctx, listFxRatesForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FxRate
	for rows.Next() {
		var i FxRate
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.YearMonth,
			&i.Currency,
			&i.Rate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoldsForExport = `-- name: ListGoldsForExport :many
SELECT d.investment_id, d.form, d.purity FROM gold_details d
JOIN investments i ON i.id = d.investment_id
WHERE i.household_id = $1
  AND (i.deleted_at IS NULL OR $2::bool)
ORDER BY d.investment_id
`

type ListGoldsForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListGoldsForExport(ctx context.Context, arg ListGoldsForExportParams) ([]GoldDetail, error) {
	rows, err := q.db.Query(ctx, listGoldsForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoldDetail
	for rows.Next() {
		var i GoldDetail
		if err := rows.Scan(&i.InvestmentID, &i.Form, &i.Purity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeForExport = `-- name: ListIncomeForExport :many
SELECT id, household_id, date, amount, currency, category, description, ownership_type, sole_owner_user_id, created_by, created_at, updated_by, updated_at, deleted_at, regularity FROM income
WHERE household_id = $1
  AND (deleted_at IS NULL OR $2::bool)
ORDER BY date, id
`

type ListIncomeForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListIncomeForExport(ctx context.Context, arg ListIncomeForExportParams) ([]Income, error) {
	rows, err := q.db.Query(ctx, listIncomeForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Income
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Date,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.Description,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Regularity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentSnapshotsForExport = `-- name: ListInvestmentSnapshotsForExport :many
SELECT s.id, s.investment_id, s.year_month, s.amount, s.currency, s.quantity, s.price_per_unit, s.accrued_interest, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at FROM investment_snapshots s
JOIN investments i ON i.id = s.investment_id
WHERE i.household_id = $1
  AND ($2::bool OR (s.deleted_at IS NULL AND i.deleted_at IS NULL))
ORDER BY s.investment_id, s.year_month, s.id
`

type ListInvestmentSnapshotsForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListInvestmentSnapshotsForExport(ctx context.Context, arg ListInvestmentSnapshotsForExportParams) ([]InvestmentSnapshot, error) {
	rows, err := q.db.Query(ctx, listInvestmentSnapshotsForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvestmentSnapshot
	for rows.Next() {
		var i InvestmentSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.InvestmentID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.Quantity,
			&i.PricePerUnit,
			&i.AccruedInterest,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentTransactionsForExport = `-- name: ListInvestmentTransactionsForExport :many
SELECT t.id, t.investment_id, t.transaction_type, t.transaction_date, t.currency, t.description, t.amount, t.quantity, t.price_per_unit, t.principal_amount, t.interest_amount, t.principal_disposition, t.interest_disposition, t.created_by, t.created_at, t.updated_by, t.updated_at, t.deleted_at FROM investment_transactions t
JOIN investments i ON i.id = t.investment_id
WHERE i.household_id = $1
  AND ($2::bool OR (t.deleted_at IS NULL AND i.deleted_at IS NULL))
ORDER BY t.investment_id, t.transaction_date, t.id
`

type ListInvestmentTransactionsForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListInvestmentTransactionsForExport(ctx context.Context, arg ListInvestmentTransactionsForExportParams) ([]InvestmentTransaction, error) {
	rows, err := q.db.Query(ctx, listInvestmentTransactionsForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvestmentTransaction
	for rows.Next() {
		var i InvestmentTransaction
		if err := rows.Scan(
			&i.ID,
			&i.InvestmentID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.Currency,
			&i.Description,
			&i.Amount,
			&i.Quantity,
			&i.PricePerUnit,
			&i.PrincipalAmount,
			&i.InterestAmount,
			&i.PrincipalDisposition,
			&i.InterestDisposition,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentsForExport = `-- name: ListInvestmentsForExport :many
SELECT id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, created_by, created_at, updated_by, updated_at, deleted_at, risk_profile, rolled_from_investment_id, tag_id FROM investments
WHERE household_id = $1
  AND (deleted_at IS NULL OR $2::bool)
ORDER BY created_at, id
`

type ListInvestmentsForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListInvestmentsForExport(ctx context.Context, arg ListInvestmentsForExportParams) ([]Investment, error) {
	rows, err := q.db.Query(ctx, listInvestmentsForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Investment
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.DisplayName,
			&i.Description,
			&i.Subtype,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
			&i.NativeCurrency,
			&i.Status,
			&i.TerminatedAt,
			&i.TerminationNote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RiskProfile,
			&i.RolledFromInvestmentID,
			&i.TagID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiabilitiesForExport = `-- name: ListLiabilitiesForExport :many
SELECT id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, counterparty_name, principal, interest_rate, term_months, start_date, maturity_date, created_by, created_at, updated_by, updated_at, deleted_at, tag_id FROM liabilities
WHERE household_id = $1
  AND (deleted_at IS NULL OR $2::bool)
ORDER BY created_at, id
`

type ListLiabilitiesForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListLiabilitiesForExport(ctx context.Context, arg ListLiabilitiesForExportParams) ([]Liability, error) {
	rows, err := q.db.Query(ctx, listLiabilitiesForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Liability
	for rows.Next() {
		var i Liability
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.DisplayName,
			&i.Description,
			&i.Subtype,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
			&i.NativeCurrency,
			&i.Status,
			&i.TerminatedAt,
			&i.TerminationNote,
			&i.CounterpartyName,
			&i.Principal,
			&i.InterestRate,
			&i.TermMonths,
			&i.StartDate,
			&i.MaturityDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TagID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiabilitySnapshotsForExport = `-- name: ListLiabilitySnapshotsForExport :many
SELECT s.id, s.liability_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at FROM liability_snapshots s
JOIN liabilities l ON l.id = s.liability_id
WHERE l.household_id = $1
  AND ($2::bool OR (s.deleted_at IS NULL AND l.deleted_at IS NULL))
ORDER BY s.liability_id, s.year_month, s.id
`

type ListLiabilitySnapshotsForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListLiabilitySnapshotsForExport(ctx context.Context, arg ListLiabilitySnapshotsForExportParams) ([]LiabilitySnapshot, error) {
	rows, err := q.db.Query(ctx, listLiabilitySnapshotsForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiabilitySnapshot
	for rows.Next() {
		var i LiabilitySnapshot
		if err := rows.Scan(
			&i.ID,
			&i.LiabilityID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMutualFundsForExport = `-- name: ListMutualFundsForExport :many
SELECT d.investment_id, d.fund_code, d.fund_manager, d.fund_type FROM mutual_fund_details d
JOIN investments i ON i.id = d.investment_id
WHERE i.household_id = $1
  AND (i.deleted_at IS NULL OR $2::bool)
ORDER BY d.investment_id
`

type ListMutualFundsForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListMutualFundsForExport(ctx context.Context, arg ListMutualFundsForExportParams) ([]MutualFundDetail, error) {
	rows, err := q.db.Query(ctx, listMutualFundsForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MutualFundDetail
	for rows.Next() {
		var i MutualFundDetail
		if err := rows.Scan(
			&i.InvestmentID,
			&i.FundCode,
			&i.FundManager,
			&i.FundType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropertiesForExport = `-- name: ListPropertiesForExport :many
SELECT d.asset_id, d.property_type, d.address, d.acquisition_date, d.acquisition_cost, d.annual_appreciation_rate FROM property_details d
JOIN assets a ON a.id = d.asset_id
WHERE a.household_id = $1
  AND (a.deleted_at IS NULL OR $2::bool)
ORDER BY d.asset_id
`

type ListPropertiesForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListPropertiesForExport(ctx context.Context, arg ListPropertiesForExportParams) ([]PropertyDetail, error) {
	rows, err := q.db.Query(ctx, listPropertiesForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PropertyDetail
	for rows.Next() {
		var i PropertyDetail
		if err := rows.Scan(
			&i.AssetID,
			&i.PropertyType,
			&i.Address,
			&i.AcquisitionDate,
			&i.AcquisitionCost,
			&i.AnnualAppreciationRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivableSnapshotsForExport = `-- name: ListReceivableSnapshotsForExport :many
SELECT s.id, s.receivable_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at FROM receivable_snapshots s
JOIN receivables r ON r.id = s.receivable_id
WHERE r.household_id = $1
  AND ($2::bool OR (s.deleted_at IS NULL AND r.deleted_at IS NULL))
ORDER BY s.receivable_id, s.year_month, s.id
`

type ListReceivableSnapshotsForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListReceivableSnapshotsForExport(ctx context.Context, arg ListReceivableSnapshotsForExportParams) ([]ReceivableSnapshot, error) {
	rows, err := q.db.Query(ctx, listReceivableSnapshotsForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceivableSnapshot
	for rows.Next() {
		var i ReceivableSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ReceivableID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivablesForExport = `-- name: ListReceivablesForExport :many
SELECT id, household_id, display_name, description, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, counterparty_name, due_date, created_by, created_at, updated_by, updated_at, deleted_at, tag_id FROM receivables
WHERE household_id = $1
  AND (deleted_at IS NULL OR $2::bool)
ORDER BY created_at, id
`

type ListReceivablesForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListReceivablesForExport(ctx context.Context, arg ListReceivablesForExportParams) ([]Receivable, error) {
	rows, err := q.db.Query(ctx, listReceivablesForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receivable
	for rows.Next() {
		var i Receivable
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.DisplayName,
			&i.Description,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
			&i.NativeCurrency,
			&i.Status,
			&i.TerminatedAt,
			&i.TerminationNote,
			&i.CounterpartyName,
			&i.DueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TagID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStocksForExport = `-- name: ListStocksForExport :many

SELECT d.investment_id, d.ticker, d.exchange FROM stock_details d
JOIN investments i ON i.id = d.investment_id
WHERE i.household_id = $1
  AND (i.deleted_at IS NULL OR $2::bool)
ORDER BY d.investment_id
`

type ListStocksForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

// ----- Investment detail tables (scoped via investments) ------------------
func (q *Queries) ListStocksForExport(ctx context.Context, arg ListStocksForExportParams) ([]StockDetail, error) {
	rows, err := q.db.Query(ctx, listStocksForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockDetail
	for rows.Next() {
		var i StockDetail
		if err := rows.Scan(&i.InvestmentID, &i.Ticker, &i.Exchange); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForExport = `-- name: ListTagsForExport :many
SELECT id, household_id, name, color, created_by, created_at, updated_by, updated_at, deleted_at FROM tags
WHERE household_id = $1
  AND (deleted_at IS NULL OR $2::bool)
ORDER BY created_at, id
`

type ListTagsForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListTagsForExport(ctx context.Context, arg ListTagsForExportParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Color,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeDepositsForExport = `-- name: ListTimeDepositsForExport :many
SELECT d.investment_id, d.bank_name, d.principal, d.interest_rate, d.term_months, d.placement_date, d.maturity_date, d.rollover_policy FROM time_deposit_details d
JOIN investments i ON i.id = d.investment_id
WHERE i.household_id = $1
  AND (i.deleted_at IS NULL OR $2::bool)
ORDER BY d.investment_id
`

type ListTimeDepositsForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListTimeDepositsForExport(ctx context.Context, arg ListTimeDepositsForExportParams) ([]TimeDepositDetail, error) {
	rows, err := q.db.Query(ctx, listTimeDepositsForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeDepositDetail
	for rows.Next() {
		var i TimeDepositDetail
		if err := rows.Scan(
			&i.InvestmentID,
			&i.BankName,
			&i.Principal,
			&i.InterestRate,
			&i.TermMonths,
			&i.PlacementDate,
			&i.MaturityDate,
			&i.RolloverPolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForExport = `-- name: ListUsersForExport :many
SELECT id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at, nickname, picture_url, theme, carryover_date_mode FROM users
WHERE household_id = $1
  AND (deleted_at IS NULL OR $2::bool)
ORDER BY created_at, id
`

type ListUsersForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListUsersForExport(ctx context.Context, arg ListUsersForExportParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.DisplayName,
			&i.Email,
			&i.GoogleSub,
			&i.Locale,
			&i.TimeZone,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Nickname,
			&i.PictureUrl,
			&i.Theme,
			&i.CarryoverDateMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesForExport = `-- name: ListVehiclesForExport :many
SELECT d.asset_id, d.vehicle_type, d.make, d.model, d.year, d.plate_number, d.annual_depreciation_rate FROM vehicle_details d
JOIN assets a ON a.id = d.asset_id
WHERE a.household_id = $1
  AND (a.deleted_at IS NULL OR $2::bool)
ORDER BY d.asset_id
`

type ListVehiclesForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListVehiclesForExport(ctx context.Context, arg ListVehiclesForExportParams) ([]VehicleDetail, error) {
	rows, err := q.db.Query(ctx, listVehiclesForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleDetail
	for rows.Next() {
		var i VehicleDetail
		if err := rows.Scan(
			&i.AssetID,
			&i.VehicleType,
			&i.Make,
			&i.Model,
			&i.Year,
			&i.PlateNumber,
			&i.AnnualDepreciationRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
