// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inflation_rates.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createInflationRate = `-- name: CreateInflationRate :one

INSERT INTO inflation_rates (
    household_id, year_month, rate, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $4
)
RETURNING id, household_id, year_month, rate, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateInflationRateParams struct {
	HouseholdID uuid.UUID       `json:"household_id"`
	YearMonth   time.Time       `json:"year_month"`
	Rate        decimal.Decimal `json:"rate"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
}

// Manual monthly inflation rates (ADR-0048). Household-scoped; `rate` is an
// annualized (YoY) percentage for that month (may be negative — deflation).
// year_month is the identity (one rate per month) — to change it, delete and
// recreate; UpdateInflationRate edits only the rate. Feeds Fund Resilience.
func (q *Queries) CreateInflationRate(ctx context.Context, arg CreateInflationRateParams) (InflationRate, error) {
	row := q.db.QueryRow(ctx, createInflationRate,
		arg.HouseholdID,
		arg.YearMonth,
		arg.Rate,
		arg.CreatedBy,
	)
	var i InflationRate
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.YearMonth,
		&i.Rate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInflationRateByID = `-- name: GetInflationRateByID :one
SELECT id, household_id, year_month, rate, created_by, created_at, updated_by, updated_at, deleted_at
FROM inflation_rates
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetInflationRateByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetInflationRateByID(ctx context.Context, arg GetInflationRateByIDParams) (InflationRate, error) {
	row := q.db.QueryRow(ctx, getInflationRateByID, arg.ID, arg.HouseholdID)
	var i InflationRate
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.YearMonth,
		&i.Rate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listInflationRatesByHousehold = `-- name: ListInflationRatesByHousehold :many
SELECT id, household_id, year_month, rate, created_by, created_at, updated_by, updated_at, deleted_at
FROM inflation_rates
WHERE household_id = $1 AND deleted_at IS NULL
ORDER BY year_month DESC
`

func (q *Queries) ListInflationRatesByHousehold(ctx context.Context, householdID uuid.UUID) ([]InflationRate, error) {
	rows, err := q.db.Query(ctx, listInflationRatesByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InflationRate
	for rows.Next() {
		var i InflationRate
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.YearMonth,
			&i.Rate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInflationRatesForExport = `-- name: ListInflationRatesForExport :many
SELECT id, household_id, year_month, rate, created_by, created_at, updated_by, updated_at, deleted_at FROM inflation_rates
WHERE household_id = $1
  AND (deleted_at IS NULL OR $2::bool)
ORDER BY year_month, id
`

type ListInflationRatesForExportParams struct {
	HouseholdID    uuid.UUID `json:"household_id"`
	IncludeDeleted bool      `json:"include_deleted"`
}

func (q *Queries) ListInflationRatesForExport(ctx context.Context, arg ListInflationRatesForExportParams) ([]InflationRate, error) {
	rows, err := q.db.Query(ctx, listInflationRatesForExport, arg.HouseholdID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InflationRate
	for rows.Next() {
		var i InflationRate
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.YearMonth,
			&i.Rate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteInflationRate = `-- name: SoftDeleteInflationRate :execrows
UPDATE inflation_rates
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type SoftDeleteInflationRateParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteInflationRate(ctx context.Context, arg SoftDeleteInflationRateParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteInflationRate, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInflationRate = `-- name: UpdateInflationRate :one
UPDATE inflation_rates
SET rate       = $3,
    updated_by = $4,
    updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING id, household_id, year_month, rate, created_by, created_at, updated_by, updated_at, deleted_at
`

type UpdateInflationRateParams struct {
	ID          uuid.UUID       `json:"id"`
	HouseholdID uuid.UUID       `json:"household_id"`
	Rate        decimal.Decimal `json:"rate"`
	UpdatedBy   *uuid.UUID      `json:"updated_by"`
}

func (q *Queries) UpdateInflationRate(ctx context.Context, arg UpdateInflationRateParams) (InflationRate, error) {
	row := q.db.QueryRow(ctx, updateInflationRate,
		arg.ID,
		arg.HouseholdID,
		arg.Rate,
		arg.UpdatedBy,
	)
	var i InflationRate
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.YearMonth,
		&i.Rate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
