// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investment_transactions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const cascadeSoftDeleteInvestmentTransactions = `-- name: CascadeSoftDeleteInvestmentTransactions :execrows
UPDATE investment_transactions t
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
FROM investments i
WHERE t.investment_id = $1
  AND t.investment_id = i.id
  AND i.household_id = $2
  AND i.deleted_at IS NULL
  AND t.deleted_at IS NULL
`

type CascadeSoftDeleteInvestmentTransactionsParams struct {
	InvestmentID uuid.UUID  `json:"investment_id"`
	HouseholdID  uuid.UUID  `json:"household_id"`
	UpdatedBy    *uuid.UUID `json:"updated_by"`
}

// CascadeSoftDeleteInvestmentTransactions tombstones every live transaction of
// one investment — see CascadeSoftDeleteAssetSnapshots for the ordering
// contract and why the already-deleted child is left alone
// (INV-SOFT-DELETE-05). This is the table the confirmed #575 orphan lived in:
// a duplicate investment deleted 17s after creation kept its live `buy`.
func (q *Queries) CascadeSoftDeleteInvestmentTransactions(ctx context.Context, arg CascadeSoftDeleteInvestmentTransactionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cascadeSoftDeleteInvestmentTransactions, arg.InvestmentID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createInvestmentTransaction = `-- name: CreateInvestmentTransaction :one

WITH owned_investment AS (
    SELECT i.id AS iid
    FROM investments i
    WHERE i.id = $1 AND i.household_id = $14::uuid AND i.deleted_at IS NULL
)
INSERT INTO investment_transactions (
    investment_id, transaction_type, transaction_date, currency, description,
    amount, quantity, price_per_unit,
    principal_amount, interest_amount,
    principal_disposition, interest_disposition,
    created_by, updated_by
)
SELECT owned_investment.iid, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $13
FROM owned_investment
RETURNING id, investment_id, transaction_type, transaction_date, currency, description, amount, quantity, price_per_unit, principal_amount, interest_amount, principal_disposition, interest_disposition, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateInvestmentTransactionParams struct {
	ID                   uuid.UUID        `json:"id"`
	TransactionType      string           `json:"transaction_type"`
	TransactionDate      time.Time        `json:"transaction_date"`
	Currency             string           `json:"currency"`
	Description          *string          `json:"description"`
	Amount               *decimal.Decimal `json:"amount"`
	Quantity             *decimal.Decimal `json:"quantity"`
	PricePerUnit         *decimal.Decimal `json:"price_per_unit"`
	PrincipalAmount      *decimal.Decimal `json:"principal_amount"`
	InterestAmount       *decimal.Decimal `json:"interest_amount"`
	PrincipalDisposition *string          `json:"principal_disposition"`
	InterestDisposition  *string          `json:"interest_disposition"`
	CreatedBy            *uuid.UUID       `json:"created_by"`
	HouseholdID          uuid.UUID        `json:"household_id"`
}

// All transaction queries verify the parent investment belongs to the
// requesting Household. Belt + suspenders on top of the application-layer
// tenancy middleware: even if a handler forgets to filter, SQL will not
// expose or mutate transactions from another Household. The transaction_type
// → shape mapping is enforced at the column level by the table's CHECK
// constraint and at the subtype level by the repository (per ADR-0003 +
// ADR-0009 + ADR-0022).
func (q *Queries) CreateInvestmentTransaction(ctx context.Context, arg CreateInvestmentTransactionParams) (InvestmentTransaction, error) {
	row := q.db.QueryRow(ctx, createInvestmentTransaction,
		arg.ID,
		arg.TransactionType,
		arg.TransactionDate,
		arg.Currency,
		arg.Description,
		arg.Amount,
		arg.Quantity,
		arg.PricePerUnit,
		arg.PrincipalAmount,
		arg.InterestAmount,
		arg.PrincipalDisposition,
		arg.InterestDisposition,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i InvestmentTransaction
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.Currency,
		&i.Description,
		&i.Amount,
		&i.Quantity,
		&i.PricePerUnit,
		&i.PrincipalAmount,
		&i.InterestAmount,
		&i.PrincipalDisposition,
		&i.InterestDisposition,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvestmentTransactionByID = `-- name: GetInvestmentTransactionByID :one
SELECT t.id, t.investment_id, t.transaction_type, t.transaction_date, t.currency, t.description, t.amount, t.quantity, t.price_per_unit, t.principal_amount, t.interest_amount, t.principal_disposition, t.interest_disposition, t.created_by, t.created_at, t.updated_by, t.updated_at, t.deleted_at
FROM investment_transactions t
JOIN investments i ON i.id = t.investment_id
WHERE t.id = $1
  AND i.household_id = $2
  AND i.deleted_at IS NULL
  AND t.deleted_at IS NULL
`

type GetInvestmentTransactionByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetInvestmentTransactionByID(ctx context.Context, arg GetInvestmentTransactionByIDParams) (InvestmentTransaction, error) {
	row := q.db.QueryRow(ctx, getInvestmentTransactionByID, arg.ID, arg.HouseholdID)
	var i InvestmentTransaction
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.Currency,
		&i.Description,
		&i.Amount,
		&i.Quantity,
		&i.PricePerUnit,
		&i.PrincipalAmount,
		&i.InterestAmount,
		&i.PrincipalDisposition,
		&i.InterestDisposition,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listInvestmentTransactionsByInvestmentIDs = `-- name: ListInvestmentTransactionsByInvestmentIDs :many
SELECT id, investment_id, transaction_type, transaction_date, currency, description, amount, quantity, price_per_unit, principal_amount, interest_amount, principal_disposition, interest_disposition, created_by, created_at, updated_by, updated_at, deleted_at
FROM investment_transactions
WHERE investment_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY investment_id, transaction_date, created_at
`

// Batch fetch of all (non-deleted) transactions across many investments, for
// list-view cost-basis aggregates (issue #18). The caller supplies only
// Household-scoped IDs (built from ListInvestmentsByHousehold), so this mirrors
// ListLatestInvestmentSnapshotsByInvestmentIDs and skips the household JOIN.
// Ascending by date so the repo can replay the avg-cost ledger in order.
func (q *Queries) ListInvestmentTransactionsByInvestmentIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]InvestmentTransaction, error) {
	rows, err := q.db.Query(ctx, listInvestmentTransactionsByInvestmentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvestmentTransaction
	for rows.Next() {
		var i InvestmentTransaction
		if err := rows.Scan(
			&i.ID,
			&i.InvestmentID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.Currency,
			&i.Description,
			&i.Amount,
			&i.Quantity,
			&i.PricePerUnit,
			&i.PrincipalAmount,
			&i.InterestAmount,
			&i.PrincipalDisposition,
			&i.InterestDisposition,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentTransactionsForInvestment = `-- name: ListInvestmentTransactionsForInvestment :many
SELECT t.id, t.investment_id, t.transaction_type, t.transaction_date, t.currency, t.description, t.amount, t.quantity, t.price_per_unit, t.principal_amount, t.interest_amount, t.principal_disposition, t.interest_disposition, t.created_by, t.created_at, t.updated_by, t.updated_at, t.deleted_at
FROM investment_transactions t
JOIN investments i ON i.id = t.investment_id
WHERE t.investment_id = $1
  AND i.household_id = $2
  AND i.deleted_at IS NULL
  AND t.deleted_at IS NULL
ORDER BY t.transaction_date DESC, t.created_at DESC
`

type ListInvestmentTransactionsForInvestmentParams struct {
	InvestmentID uuid.UUID `json:"investment_id"`
	HouseholdID  uuid.UUID `json:"household_id"`
}

func (q *Queries) ListInvestmentTransactionsForInvestment(ctx context.Context, arg ListInvestmentTransactionsForInvestmentParams) ([]InvestmentTransaction, error) {
	rows, err := q.db.Query(ctx, listInvestmentTransactionsForInvestment, arg.InvestmentID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvestmentTransaction
	for rows.Next() {
		var i InvestmentTransaction
		if err := rows.Scan(
			&i.ID,
			&i.InvestmentID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.Currency,
			&i.Description,
			&i.Amount,
			&i.Quantity,
			&i.PricePerUnit,
			&i.PrincipalAmount,
			&i.InterestAmount,
			&i.PrincipalDisposition,
			&i.InterestDisposition,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteInvestmentTransaction = `-- name: SoftDeleteInvestmentTransaction :execrows
UPDATE investment_transactions t
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
FROM investments i
WHERE t.id = $1
  AND t.investment_id = i.id
  AND i.household_id = $2
  AND i.deleted_at IS NULL
  AND t.deleted_at IS NULL
`

type SoftDeleteInvestmentTransactionParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteInvestmentTransaction(ctx context.Context, arg SoftDeleteInvestmentTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteInvestmentTransaction, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInvestmentTransaction = `-- name: UpdateInvestmentTransaction :one
UPDATE investment_transactions t
SET transaction_date      = $3,
    currency              = $4,
    description           = $5,
    amount                = $6,
    quantity              = $7,
    price_per_unit        = $8,
    principal_amount      = $9,
    interest_amount       = $10,
    principal_disposition = $11,
    interest_disposition  = $12,
    updated_by            = $13,
    updated_at            = now()
FROM investments i
WHERE t.id = $1
  AND t.investment_id = i.id
  AND i.household_id = $2
  AND i.deleted_at IS NULL
  AND t.deleted_at IS NULL
RETURNING t.id, t.investment_id, t.transaction_type, t.transaction_date, t.currency, t.description, t.amount, t.quantity, t.price_per_unit, t.principal_amount, t.interest_amount, t.principal_disposition, t.interest_disposition, t.created_by, t.created_at, t.updated_by, t.updated_at, t.deleted_at
`

type UpdateInvestmentTransactionParams struct {
	ID                   uuid.UUID        `json:"id"`
	HouseholdID          uuid.UUID        `json:"household_id"`
	TransactionDate      time.Time        `json:"transaction_date"`
	Currency             string           `json:"currency"`
	Description          *string          `json:"description"`
	Amount               *decimal.Decimal `json:"amount"`
	Quantity             *decimal.Decimal `json:"quantity"`
	PricePerUnit         *decimal.Decimal `json:"price_per_unit"`
	PrincipalAmount      *decimal.Decimal `json:"principal_amount"`
	InterestAmount       *decimal.Decimal `json:"interest_amount"`
	PrincipalDisposition *string          `json:"principal_disposition"`
	InterestDisposition  *string          `json:"interest_disposition"`
	UpdatedBy            *uuid.UUID       `json:"updated_by"`
}

func (q *Queries) UpdateInvestmentTransaction(ctx context.Context, arg UpdateInvestmentTransactionParams) (InvestmentTransaction, error) {
	row := q.db.QueryRow(ctx, updateInvestmentTransaction,
		arg.ID,
		arg.HouseholdID,
		arg.TransactionDate,
		arg.Currency,
		arg.Description,
		arg.Amount,
		arg.Quantity,
		arg.PricePerUnit,
		arg.PrincipalAmount,
		arg.InterestAmount,
		arg.PrincipalDisposition,
		arg.InterestDisposition,
		arg.UpdatedBy,
	)
	var i InvestmentTransaction
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.Currency,
		&i.Description,
		&i.Amount,
		&i.Quantity,
		&i.PricePerUnit,
		&i.PrincipalAmount,
		&i.InterestAmount,
		&i.PrincipalDisposition,
		&i.InterestDisposition,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
