// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investment_snapshots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createInvestmentSnapshot = `-- name: CreateInvestmentSnapshot :one

WITH owned_investment AS (
    SELECT i.id AS iid
    FROM investments i
    WHERE i.id = $1 AND i.household_id = $11::uuid AND i.deleted_at IS NULL
)
INSERT INTO investment_snapshots (
    investment_id, year_month, amount, currency,
    quantity, price_per_unit, accrued_interest,
    as_of_date, description,
    created_by, updated_by
)
SELECT owned_investment.iid, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10
FROM owned_investment
RETURNING id, investment_id, year_month, amount, currency, quantity, price_per_unit, accrued_interest, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateInvestmentSnapshotParams struct {
	ID              uuid.UUID        `json:"id"`
	YearMonth       time.Time        `json:"year_month"`
	Amount          decimal.Decimal  `json:"amount"`
	Currency        string           `json:"currency"`
	Quantity        *decimal.Decimal `json:"quantity"`
	PricePerUnit    *decimal.Decimal `json:"price_per_unit"`
	AccruedInterest *decimal.Decimal `json:"accrued_interest"`
	AsOfDate        *time.Time       `json:"as_of_date"`
	Description     *string          `json:"description"`
	CreatedBy       *uuid.UUID       `json:"created_by"`
	HouseholdID     uuid.UUID        `json:"household_id"`
}

// All snapshot queries verify the parent investment belongs to the requesting
// Household. This is belt + suspenders on top of the application-layer
// tenancy middleware: even if a handler forgets to filter, SQL will not
// expose or mutate snapshots from another Household. The XOR shape
// (quantity+price vs accrued_interest) is enforced at the column level by
// the table's CHECK constraint and at the subtype level by the repository
// (per ADR-0022).
func (q *Queries) CreateInvestmentSnapshot(ctx context.Context, arg CreateInvestmentSnapshotParams) (InvestmentSnapshot, error) {
	row := q.db.QueryRow(ctx, createInvestmentSnapshot,
		arg.ID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.Quantity,
		arg.PricePerUnit,
		arg.AccruedInterest,
		arg.AsOfDate,
		arg.Description,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i InvestmentSnapshot
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.Quantity,
		&i.PricePerUnit,
		&i.AccruedInterest,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvestmentSnapshotByID = `-- name: GetInvestmentSnapshotByID :one
SELECT s.id, s.investment_id, s.year_month, s.amount, s.currency, s.quantity, s.price_per_unit, s.accrued_interest, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM investment_snapshots s
JOIN investments i ON i.id = s.investment_id
WHERE s.id = $1
  AND i.household_id = $2
  AND i.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type GetInvestmentSnapshotByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetInvestmentSnapshotByID(ctx context.Context, arg GetInvestmentSnapshotByIDParams) (InvestmentSnapshot, error) {
	row := q.db.QueryRow(ctx, getInvestmentSnapshotByID, arg.ID, arg.HouseholdID)
	var i InvestmentSnapshot
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.Quantity,
		&i.PricePerUnit,
		&i.AccruedInterest,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEligibleQtyPriceInvestmentIDsForMonth = `-- name: ListEligibleQtyPriceInvestmentIDsForMonth :many

SELECT id
FROM investments
WHERE household_id = $1::uuid
  AND deleted_at IS NULL
  AND subtype IN ('stock', 'mutual_fund', 'gold')
  AND (terminated_at IS NULL OR terminated_at >= $2::date)
`

type ListEligibleQtyPriceInvestmentIDsForMonthParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	YearMonth   time.Time `json:"year_month"`
}

// ----- bulk monthly-entry, qty×price shape (ADR-0046, #423) ------------------
//
// Stock/MutualFund/Gold only: the three subtypes whose snapshots take the
// quantity+price_per_unit branch of investment_snapshot_shape. Bond/TimeDeposit
// (the accrued branch) are a separate slice (#424) with their own queries.
// Eligibility mirrors the asset rule: owned, not deleted, and either still
// active or terminated in the target month or later. created_at is deliberately
// not gated (a record timestamp, not economic existence — see the asset notes).
func (q *Queries) ListEligibleQtyPriceInvestmentIDsForMonth(ctx context.Context, arg ListEligibleQtyPriceInvestmentIDsForMonthParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEligibleQtyPriceInvestmentIDsForMonth, arg.HouseholdID, arg.YearMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleQtyPriceInvestmentsForMonth = `-- name: ListEligibleQtyPriceInvestmentsForMonth :many
SELECT id, display_name, native_currency, subtype, ownership_type, sole_owner_user_id
FROM investments
WHERE household_id = $1::uuid
  AND deleted_at IS NULL
  AND subtype IN ('stock', 'mutual_fund', 'gold')
  AND (terminated_at IS NULL OR terminated_at >= $2::date)
ORDER BY subtype, display_name
`

type ListEligibleQtyPriceInvestmentsForMonthParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	YearMonth   time.Time `json:"year_month"`
}

type ListEligibleQtyPriceInvestmentsForMonthRow struct {
	ID              uuid.UUID  `json:"id"`
	DisplayName     string     `json:"display_name"`
	NativeCurrency  string     `json:"native_currency"`
	Subtype         string     `json:"subtype"`
	OwnershipType   string     `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID `json:"sole_owner_user_id"`
}

// ListEligibleQtyPriceInvestmentsForMonth is the ID query plus the display
// fields the entry list needs (ADR-0046): name, native currency, and subtype so
// the entry view groups by type. Ordered by subtype then name so rows arrive
// pre-grouped; the entry view re-orders subtypes to its own preference.
func (q *Queries) ListEligibleQtyPriceInvestmentsForMonth(ctx context.Context, arg ListEligibleQtyPriceInvestmentsForMonthParams) ([]ListEligibleQtyPriceInvestmentsForMonthRow, error) {
	rows, err := q.db.Query(ctx, listEligibleQtyPriceInvestmentsForMonth, arg.HouseholdID, arg.YearMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleQtyPriceInvestmentsForMonthRow
	for rows.Next() {
		var i ListEligibleQtyPriceInvestmentsForMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.NativeCurrency,
			&i.Subtype,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentSnapshotsByInvestmentIDs = `-- name: ListInvestmentSnapshotsByInvestmentIDs :many
SELECT id, investment_id, year_month, amount, currency, quantity, price_per_unit, accrued_interest, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
FROM investment_snapshots
WHERE investment_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY investment_id, year_month
`

// Batch fetch of every (non-deleted) snapshot across many investments, for the
// list/home time-graph value + cost series (issue #22). Household-scoped IDs
// supplied by the caller (mirrors ListLatestInvestmentSnapshotsByInvestmentIDs).
// Ascending by year_month so the repo can build each series in order.
func (q *Queries) ListInvestmentSnapshotsByInvestmentIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]InvestmentSnapshot, error) {
	rows, err := q.db.Query(ctx, listInvestmentSnapshotsByInvestmentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvestmentSnapshot
	for rows.Next() {
		var i InvestmentSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.InvestmentID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.Quantity,
			&i.PricePerUnit,
			&i.AccruedInterest,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentSnapshotsForInvestment = `-- name: ListInvestmentSnapshotsForInvestment :many
SELECT s.id, s.investment_id, s.year_month, s.amount, s.currency, s.quantity, s.price_per_unit, s.accrued_interest, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM investment_snapshots s
JOIN investments i ON i.id = s.investment_id
WHERE s.investment_id = $1
  AND i.household_id = $2
  AND i.deleted_at IS NULL
  AND s.deleted_at IS NULL
ORDER BY s.year_month DESC
`

type ListInvestmentSnapshotsForInvestmentParams struct {
	InvestmentID uuid.UUID `json:"investment_id"`
	HouseholdID  uuid.UUID `json:"household_id"`
}

func (q *Queries) ListInvestmentSnapshotsForInvestment(ctx context.Context, arg ListInvestmentSnapshotsForInvestmentParams) ([]InvestmentSnapshot, error) {
	rows, err := q.db.Query(ctx, listInvestmentSnapshotsForInvestment, arg.InvestmentID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvestmentSnapshot
	for rows.Next() {
		var i InvestmentSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.InvestmentID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.Quantity,
			&i.PricePerUnit,
			&i.AccruedInterest,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestInvestmentSnapshotsByInvestmentIDs = `-- name: ListLatestInvestmentSnapshotsByInvestmentIDs :many
SELECT DISTINCT ON (investment_id) id, investment_id, year_month, amount, currency, quantity, price_per_unit, accrued_interest, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
FROM investment_snapshots
WHERE investment_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY investment_id, year_month DESC
`

// Batch fetch of the most-recent snapshot per investment, for list views.
func (q *Queries) ListLatestInvestmentSnapshotsByInvestmentIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]InvestmentSnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestInvestmentSnapshotsByInvestmentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvestmentSnapshot
	for rows.Next() {
		var i InvestmentSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.InvestmentID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.Quantity,
			&i.PricePerUnit,
			&i.AccruedInterest,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestQtyPriceSnapshotsByInvestmentIDsAsOfMonth = `-- name: ListLatestQtyPriceSnapshotsByInvestmentIDsAsOfMonth :many
SELECT DISTINCT ON (investment_id) investment_id, quantity, price_per_unit, year_month
FROM investment_snapshots
WHERE investment_id = ANY($1::uuid[])
  AND deleted_at IS NULL
  AND year_month <= $2::date
ORDER BY investment_id, year_month DESC
`

type ListLatestQtyPriceSnapshotsByInvestmentIDsAsOfMonthParams struct {
	InvestmentIds []uuid.UUID `json:"investment_ids"`
	YearMonth     time.Time   `json:"year_month"`
}

type ListLatestQtyPriceSnapshotsByInvestmentIDsAsOfMonthRow struct {
	InvestmentID uuid.UUID        `json:"investment_id"`
	Quantity     *decimal.Decimal `json:"quantity"`
	PricePerUnit *decimal.Decimal `json:"price_per_unit"`
	YearMonth    time.Time        `json:"year_month"`
}

// ListLatestQtyPriceSnapshotsByInvestmentIDsAsOfMonth returns, per investment,
// the most-recent snapshot at or before the target month — the carry-forward
// prefill for the entry list. Carries quantity + price_per_unit (the two
// tab-stops), month-bounded so a value entered ahead of the target does not leak
// backwards as the prefill.
func (q *Queries) ListLatestQtyPriceSnapshotsByInvestmentIDsAsOfMonth(ctx context.Context, arg ListLatestQtyPriceSnapshotsByInvestmentIDsAsOfMonthParams) ([]ListLatestQtyPriceSnapshotsByInvestmentIDsAsOfMonthRow, error) {
	rows, err := q.db.Query(ctx, listLatestQtyPriceSnapshotsByInvestmentIDsAsOfMonth, arg.InvestmentIds, arg.YearMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestQtyPriceSnapshotsByInvestmentIDsAsOfMonthRow
	for rows.Next() {
		var i ListLatestQtyPriceSnapshotsByInvestmentIDsAsOfMonthRow
		if err := rows.Scan(
			&i.InvestmentID,
			&i.Quantity,
			&i.PricePerUnit,
			&i.YearMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteInvestmentSnapshot = `-- name: SoftDeleteInvestmentSnapshot :execrows
UPDATE investment_snapshots s
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
FROM investments i
WHERE s.id = $1
  AND s.investment_id = i.id
  AND i.household_id = $2
  AND i.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type SoftDeleteInvestmentSnapshotParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteInvestmentSnapshot(ctx context.Context, arg SoftDeleteInvestmentSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteInvestmentSnapshot, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInvestmentSnapshot = `-- name: UpdateInvestmentSnapshot :one
UPDATE investment_snapshots s
SET amount           = $3,
    currency         = $4,
    quantity         = $5,
    price_per_unit   = $6,
    accrued_interest = $7,
    as_of_date       = $8,
    description      = $9,
    updated_by       = $10,
    updated_at       = now()
FROM investments i
WHERE s.id = $1
  AND s.investment_id = i.id
  AND i.household_id = $2
  AND i.deleted_at IS NULL
  AND s.deleted_at IS NULL
RETURNING s.id, s.investment_id, s.year_month, s.amount, s.currency, s.quantity, s.price_per_unit, s.accrued_interest, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
`

type UpdateInvestmentSnapshotParams struct {
	ID              uuid.UUID        `json:"id"`
	HouseholdID     uuid.UUID        `json:"household_id"`
	Amount          decimal.Decimal  `json:"amount"`
	Currency        string           `json:"currency"`
	Quantity        *decimal.Decimal `json:"quantity"`
	PricePerUnit    *decimal.Decimal `json:"price_per_unit"`
	AccruedInterest *decimal.Decimal `json:"accrued_interest"`
	AsOfDate        *time.Time       `json:"as_of_date"`
	Description     *string          `json:"description"`
	UpdatedBy       *uuid.UUID       `json:"updated_by"`
}

func (q *Queries) UpdateInvestmentSnapshot(ctx context.Context, arg UpdateInvestmentSnapshotParams) (InvestmentSnapshot, error) {
	row := q.db.QueryRow(ctx, updateInvestmentSnapshot,
		arg.ID,
		arg.HouseholdID,
		arg.Amount,
		arg.Currency,
		arg.Quantity,
		arg.PricePerUnit,
		arg.AccruedInterest,
		arg.AsOfDate,
		arg.Description,
		arg.UpdatedBy,
	)
	var i InvestmentSnapshot
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.Quantity,
		&i.PricePerUnit,
		&i.AccruedInterest,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertInvestmentSnapshot = `-- name: UpsertInvestmentSnapshot :one
WITH owned_investment AS (
    SELECT i.id AS iid
    FROM investments i
    WHERE i.id = $1 AND i.household_id = $11::uuid AND i.deleted_at IS NULL
)
INSERT INTO investment_snapshots (
    investment_id, year_month, amount, currency,
    quantity, price_per_unit, accrued_interest,
    as_of_date, description,
    created_by, updated_by
)
SELECT owned_investment.iid, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10
FROM owned_investment
ON CONFLICT (investment_id, year_month) WHERE deleted_at IS NULL
DO UPDATE SET
    amount           = EXCLUDED.amount,
    currency         = EXCLUDED.currency,
    quantity         = EXCLUDED.quantity,
    price_per_unit   = EXCLUDED.price_per_unit,
    accrued_interest = EXCLUDED.accrued_interest,
    as_of_date       = EXCLUDED.as_of_date,
    description      = EXCLUDED.description,
    updated_by       = EXCLUDED.updated_by,
    updated_at       = now()
RETURNING id, investment_id, year_month, amount, currency, quantity, price_per_unit, accrued_interest, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
`

type UpsertInvestmentSnapshotParams struct {
	ID              uuid.UUID        `json:"id"`
	YearMonth       time.Time        `json:"year_month"`
	Amount          decimal.Decimal  `json:"amount"`
	Currency        string           `json:"currency"`
	Quantity        *decimal.Decimal `json:"quantity"`
	PricePerUnit    *decimal.Decimal `json:"price_per_unit"`
	AccruedInterest *decimal.Decimal `json:"accrued_interest"`
	AsOfDate        *time.Time       `json:"as_of_date"`
	Description     *string          `json:"description"`
	CreatedBy       *uuid.UUID       `json:"created_by"`
	HouseholdID     uuid.UUID        `json:"household_id"`
}

// UpsertInvestmentSnapshot inserts a snapshot or, when one already exists for
// the (investment_id, year_month) pair, overwrites it (last-write-wins) — the
// importer needs idempotent re-runs of a multi-year backfill. ON CONFLICT
// targets the partial unique index, so its predicate (deleted_at IS NULL) is
// repeated. The repo validates the value-column shape against the parent's
// subtype before calling this; the DB CHECK is the final backstop.
// created_by is only set on insert; updated_by always.
func (q *Queries) UpsertInvestmentSnapshot(ctx context.Context, arg UpsertInvestmentSnapshotParams) (InvestmentSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertInvestmentSnapshot,
		arg.ID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.Quantity,
		arg.PricePerUnit,
		arg.AccruedInterest,
		arg.AsOfDate,
		arg.Description,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i InvestmentSnapshot
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.Quantity,
		&i.PricePerUnit,
		&i.AccruedInterest,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
