// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: liability_snapshots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const cascadeSoftDeleteLiabilitySnapshots = `-- name: CascadeSoftDeleteLiabilitySnapshots :execrows
UPDATE liability_snapshots s
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
FROM liabilities l
WHERE s.liability_id = $1
  AND s.liability_id = l.id
  AND l.household_id = $2
  AND l.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type CascadeSoftDeleteLiabilitySnapshotsParams struct {
	LiabilityID uuid.UUID  `json:"liability_id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

// CascadeSoftDeleteLiabilitySnapshots tombstones every live snapshot of one
// liability — see CascadeSoftDeleteAssetSnapshots for the ordering contract
// and why the already-deleted child is left alone (INV-SOFT-DELETE-05).
func (q *Queries) CascadeSoftDeleteLiabilitySnapshots(ctx context.Context, arg CascadeSoftDeleteLiabilitySnapshotsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cascadeSoftDeleteLiabilitySnapshots, arg.LiabilityID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createLiabilitySnapshot = `-- name: CreateLiabilitySnapshot :one

WITH owned_liability AS (
    SELECT l.id AS lid
    FROM liabilities l
    WHERE l.id = $1 AND l.household_id = $8::uuid AND l.deleted_at IS NULL
)
INSERT INTO liability_snapshots (
    liability_id, year_month, amount, currency, as_of_date, description,
    created_by, updated_by
)
SELECT owned_liability.lid, $2, $3, $4, $5, $6, $7, $7
FROM owned_liability
RETURNING id, liability_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateLiabilitySnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	YearMonth   time.Time       `json:"year_month"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	HouseholdID uuid.UUID       `json:"household_id"`
}

// All snapshot queries verify the parent liability belongs to the requesting
// Household. This is belt + suspenders on top of the application-layer
// tenancy middleware: even if a handler forgets to filter, SQL will not
// expose or mutate snapshots from another Household.
func (q *Queries) CreateLiabilitySnapshot(ctx context.Context, arg CreateLiabilitySnapshotParams) (LiabilitySnapshot, error) {
	row := q.db.QueryRow(ctx, createLiabilitySnapshot,
		arg.ID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i LiabilitySnapshot
	err := row.Scan(
		&i.ID,
		&i.LiabilityID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArchivedLiabilitySnapshotAtMonth = `-- name: GetArchivedLiabilitySnapshotAtMonth :one
SELECT s.id, s.liability_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM liability_snapshots s
JOIN liabilities l ON l.id = s.liability_id
WHERE s.liability_id = $1
  AND s.year_month = $2::date
  AND l.household_id = $3::uuid
  AND l.deleted_at IS NULL
  AND s.deleted_at = $4::timestamptz
  AND s.amount <> 0
ORDER BY s.created_at DESC
LIMIT 1
`

type GetArchivedLiabilitySnapshotAtMonthParams struct {
	LiabilityID uuid.UUID          `json:"liability_id"`
	YearMonth   time.Time          `json:"year_month"`
	HouseholdID uuid.UUID          `json:"household_id"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) GetArchivedLiabilitySnapshotAtMonth(ctx context.Context, arg GetArchivedLiabilitySnapshotAtMonthParams) (LiabilitySnapshot, error) {
	row := q.db.QueryRow(ctx, getArchivedLiabilitySnapshotAtMonth,
		arg.LiabilityID,
		arg.YearMonth,
		arg.HouseholdID,
		arg.ArchivedAt,
	)
	var i LiabilitySnapshot
	err := row.Scan(
		&i.ID,
		&i.LiabilityID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLiabilityForImport = `-- name: GetLiabilityForImport :one
SELECT l.display_name, l.native_currency
FROM liabilities l
WHERE l.id = $1 AND l.household_id = $2 AND l.deleted_at IS NULL
`

type GetLiabilityForImportParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

type GetLiabilityForImportRow struct {
	DisplayName    string `json:"display_name"`
	NativeCurrency string `json:"native_currency"`
}

// GetLiabilityForImport returns the display name + native currency of an owned
// liability. Doubles as the ownership/existence check for the snapshot
// importer: ErrNoRows means the liability doesn't exist in this household (or
// is deleted), which the repo maps to ErrNotFound -> 404.
func (q *Queries) GetLiabilityForImport(ctx context.Context, arg GetLiabilityForImportParams) (GetLiabilityForImportRow, error) {
	row := q.db.QueryRow(ctx, getLiabilityForImport, arg.ID, arg.HouseholdID)
	var i GetLiabilityForImportRow
	err := row.Scan(&i.DisplayName, &i.NativeCurrency)
	return i, err
}

const getLiabilitySnapshotAtMonth = `-- name: GetLiabilitySnapshotAtMonth :one

SELECT s.id, s.liability_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM liability_snapshots s
JOIN liabilities l ON l.id = s.liability_id
WHERE s.liability_id = $1
  AND s.year_month = $2::date
  AND l.household_id = $3::uuid
  AND l.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type GetLiabilitySnapshotAtMonthParams struct {
	LiabilityID uuid.UUID `json:"liability_id"`
	YearMonth   time.Time `json:"year_month"`
	HouseholdID uuid.UUID `json:"household_id"`
}

// Close-snapshot displacement (ADR-0052 §2) — see asset_snapshots.sql for the
// mechanism and the reasoning behind each guard.
func (q *Queries) GetLiabilitySnapshotAtMonth(ctx context.Context, arg GetLiabilitySnapshotAtMonthParams) (LiabilitySnapshot, error) {
	row := q.db.QueryRow(ctx, getLiabilitySnapshotAtMonth, arg.LiabilityID, arg.YearMonth, arg.HouseholdID)
	var i LiabilitySnapshot
	err := row.Scan(
		&i.ID,
		&i.LiabilityID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLiabilitySnapshotByID = `-- name: GetLiabilitySnapshotByID :one
SELECT s.id, s.liability_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM liability_snapshots s
JOIN liabilities l ON l.id = s.liability_id
WHERE s.id = $1
  AND l.household_id = $2
  AND l.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type GetLiabilitySnapshotByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetLiabilitySnapshotByID(ctx context.Context, arg GetLiabilitySnapshotByIDParams) (LiabilitySnapshot, error) {
	row := q.db.QueryRow(ctx, getLiabilitySnapshotByID, arg.ID, arg.HouseholdID)
	var i LiabilitySnapshot
	err := row.Scan(
		&i.ID,
		&i.LiabilityID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEligibleLiabilitiesForMonth = `-- name: ListEligibleLiabilitiesForMonth :many
SELECT id, display_name, native_currency, subtype, ownership_type, sole_owner_user_id
FROM liabilities
WHERE household_id = $1::uuid
  AND deleted_at IS NULL
  AND (terminated_at IS NULL OR terminated_at >= $2::date)
ORDER BY subtype, display_name
`

type ListEligibleLiabilitiesForMonthParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	YearMonth   time.Time `json:"year_month"`
}

type ListEligibleLiabilitiesForMonthRow struct {
	ID              uuid.UUID  `json:"id"`
	DisplayName     string     `json:"display_name"`
	NativeCurrency  string     `json:"native_currency"`
	Subtype         string     `json:"subtype"`
	OwnershipType   string     `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID `json:"sole_owner_user_id"`
}

// ListEligibleLiabilitiesForMonth is ListEligibleLiabilityIDsForMonth plus the
// display fields the bulk monthly-entry list needs (ADR-0046): name, native
// currency, and subtype so the entry view can group by type (personal /
// institutional). Ordered by subtype then display name so rows arrive
// pre-grouped.
func (q *Queries) ListEligibleLiabilitiesForMonth(ctx context.Context, arg ListEligibleLiabilitiesForMonthParams) ([]ListEligibleLiabilitiesForMonthRow, error) {
	rows, err := q.db.Query(ctx, listEligibleLiabilitiesForMonth, arg.HouseholdID, arg.YearMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleLiabilitiesForMonthRow
	for rows.Next() {
		var i ListEligibleLiabilitiesForMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.NativeCurrency,
			&i.Subtype,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleLiabilityIDsForMonth = `-- name: ListEligibleLiabilityIDsForMonth :many
SELECT id
FROM liabilities
WHERE household_id = $1::uuid
  AND deleted_at IS NULL
  AND (terminated_at IS NULL OR terminated_at >= $2::date)
`

type ListEligibleLiabilityIDsForMonthParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	YearMonth   time.Time `json:"year_month"`
}

// ListEligibleLiabilityIDsForMonth returns the ids of the household's
// liabilities that may legitimately hold a snapshot for the given target month
// (ADR-0046 month-aware eligibility): owned, not deleted, and either still
// active or terminated in the target month or later. A liability terminated
// *before* the target month never appears — its forward contribution is already
// frozen by the carry-forward rule. No created_at guard, for the same reason as
// the Asset entry list: created_at is a record timestamp, not economic
// existence, and gating on it would block legitimate backfill/onboarding.
func (q *Queries) ListEligibleLiabilityIDsForMonth(ctx context.Context, arg ListEligibleLiabilityIDsForMonthParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEligibleLiabilityIDsForMonth, arg.HouseholdID, arg.YearMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestLiabilitySnapshotsByLiabilityIDs = `-- name: ListLatestLiabilitySnapshotsByLiabilityIDs :many
SELECT DISTINCT ON (liability_id) id, liability_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
FROM liability_snapshots
WHERE liability_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY liability_id, year_month DESC
`

// Batch fetch of the most-recent snapshot per liability, for list views.
func (q *Queries) ListLatestLiabilitySnapshotsByLiabilityIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]LiabilitySnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestLiabilitySnapshotsByLiabilityIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiabilitySnapshot
	for rows.Next() {
		var i LiabilitySnapshot
		if err := rows.Scan(
			&i.ID,
			&i.LiabilityID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestSnapshotsByLiabilityIDsAsOfMonth = `-- name: ListLatestSnapshotsByLiabilityIDsAsOfMonth :many
SELECT DISTINCT ON (liability_id) liability_id, amount, year_month
FROM liability_snapshots
WHERE liability_id = ANY($1::uuid[])
  AND deleted_at IS NULL
  AND year_month <= $2::date
ORDER BY liability_id, year_month DESC
`

type ListLatestSnapshotsByLiabilityIDsAsOfMonthParams struct {
	LiabilityIds []uuid.UUID `json:"liability_ids"`
	YearMonth    time.Time   `json:"year_month"`
}

type ListLatestSnapshotsByLiabilityIDsAsOfMonthRow struct {
	LiabilityID uuid.UUID       `json:"liability_id"`
	Amount      decimal.Decimal `json:"amount"`
	YearMonth   time.Time       `json:"year_month"`
}

// ListLatestSnapshotsByLiabilityIDsAsOfMonth returns, per liability, the
// most-recent snapshot at or before the target month — the carry-forward
// prefill for the entry list. Month-bounded so a value entered ahead of the
// target does not leak backwards as the prefill.
func (q *Queries) ListLatestSnapshotsByLiabilityIDsAsOfMonth(ctx context.Context, arg ListLatestSnapshotsByLiabilityIDsAsOfMonthParams) ([]ListLatestSnapshotsByLiabilityIDsAsOfMonthRow, error) {
	rows, err := q.db.Query(ctx, listLatestSnapshotsByLiabilityIDsAsOfMonth, arg.LiabilityIds, arg.YearMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestSnapshotsByLiabilityIDsAsOfMonthRow
	for rows.Next() {
		var i ListLatestSnapshotsByLiabilityIDsAsOfMonthRow
		if err := rows.Scan(&i.LiabilityID, &i.Amount, &i.YearMonth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiabilitySnapshotsByLiabilityIDs = `-- name: ListLiabilitySnapshotsByLiabilityIDs :many
SELECT id, liability_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
FROM liability_snapshots
WHERE liability_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY liability_id, year_month
`

// Full ascending value series per liability, for the Liabilities Home time
// graphs (epic #204). Ascending order is what LiabilityTimeSeries' carry-
// forward sampling relies on; mirrors ListAssetSnapshotsByAssetIDs.
func (q *Queries) ListLiabilitySnapshotsByLiabilityIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]LiabilitySnapshot, error) {
	rows, err := q.db.Query(ctx, listLiabilitySnapshotsByLiabilityIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiabilitySnapshot
	for rows.Next() {
		var i LiabilitySnapshot
		if err := rows.Scan(
			&i.ID,
			&i.LiabilityID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiabilitySnapshotsForLiability = `-- name: ListLiabilitySnapshotsForLiability :many
SELECT s.id, s.liability_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM liability_snapshots s
JOIN liabilities l ON l.id = s.liability_id
WHERE s.liability_id = $1
  AND l.household_id = $2
  AND l.deleted_at IS NULL
  AND s.deleted_at IS NULL
ORDER BY s.year_month DESC
`

type ListLiabilitySnapshotsForLiabilityParams struct {
	LiabilityID uuid.UUID `json:"liability_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ListLiabilitySnapshotsForLiability(ctx context.Context, arg ListLiabilitySnapshotsForLiabilityParams) ([]LiabilitySnapshot, error) {
	rows, err := q.db.Query(ctx, listLiabilitySnapshotsForLiability, arg.LiabilityID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiabilitySnapshot
	for rows.Next() {
		var i LiabilitySnapshot
		if err := rows.Scan(
			&i.ID,
			&i.LiabilityID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreLiabilitySnapshot = `-- name: RestoreLiabilitySnapshot :execrows
UPDATE liability_snapshots s
SET deleted_at = NULL,
    updated_by = $1,
    updated_at = now()
FROM liabilities l
WHERE s.id = $2
  AND s.liability_id = l.id
  AND l.household_id = $3::uuid
  AND l.deleted_at IS NULL
  AND s.deleted_at IS NOT NULL
`

type RestoreLiabilitySnapshotParams struct {
	UpdatedBy   *uuid.UUID `json:"updated_by"`
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
}

func (q *Queries) RestoreLiabilitySnapshot(ctx context.Context, arg RestoreLiabilitySnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreLiabilitySnapshot, arg.UpdatedBy, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteLiabilitySnapshot = `-- name: SoftDeleteLiabilitySnapshot :execrows
UPDATE liability_snapshots s
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
FROM liabilities l
WHERE s.id = $1
  AND s.liability_id = l.id
  AND l.household_id = $2
  AND l.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type SoftDeleteLiabilitySnapshotParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteLiabilitySnapshot(ctx context.Context, arg SoftDeleteLiabilitySnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteLiabilitySnapshot, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLiabilitySnapshot = `-- name: UpdateLiabilitySnapshot :one
UPDATE liability_snapshots s
SET amount      = $3,
    currency    = $4,
    as_of_date  = $5,
    description = $6,
    updated_by  = $7,
    updated_at  = now()
FROM liabilities l
WHERE s.id = $1
  AND s.liability_id = l.id
  AND l.household_id = $2
  AND l.deleted_at IS NULL
  AND s.deleted_at IS NULL
RETURNING s.id, s.liability_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
`

type UpdateLiabilitySnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	HouseholdID uuid.UUID       `json:"household_id"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	UpdatedBy   *uuid.UUID      `json:"updated_by"`
}

func (q *Queries) UpdateLiabilitySnapshot(ctx context.Context, arg UpdateLiabilitySnapshotParams) (LiabilitySnapshot, error) {
	row := q.db.QueryRow(ctx, updateLiabilitySnapshot,
		arg.ID,
		arg.HouseholdID,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.UpdatedBy,
	)
	var i LiabilitySnapshot
	err := row.Scan(
		&i.ID,
		&i.LiabilityID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertLiabilitySnapshot = `-- name: UpsertLiabilitySnapshot :one
WITH owned_liability AS (
    SELECT l.id AS lid
    FROM liabilities l
    WHERE l.id = $1 AND l.household_id = $8::uuid AND l.deleted_at IS NULL
)
INSERT INTO liability_snapshots (
    liability_id, year_month, amount, currency, as_of_date, description,
    created_by, updated_by
)
SELECT owned_liability.lid, $2, $3, $4, $5, $6, $7, $7
FROM owned_liability
ON CONFLICT (liability_id, year_month) WHERE deleted_at IS NULL
DO UPDATE SET
    amount      = EXCLUDED.amount,
    currency    = EXCLUDED.currency,
    as_of_date  = EXCLUDED.as_of_date,
    description = EXCLUDED.description,
    updated_by  = EXCLUDED.updated_by,
    updated_at  = now()
RETURNING id, liability_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
`

type UpsertLiabilitySnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	YearMonth   time.Time       `json:"year_month"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	HouseholdID uuid.UUID       `json:"household_id"`
}

// UpsertLiabilitySnapshot inserts a snapshot or, when one already exists for
// the (liability_id, year_month) pair, overwrites it (last-write-wins) — the
// importer needs idempotent re-runs of a multi-year backfill. ON CONFLICT
// targets the partial unique index, so its predicate (deleted_at IS NULL) is
// repeated. created_by is only set on insert; updated_by always.
func (q *Queries) UpsertLiabilitySnapshot(ctx context.Context, arg UpsertLiabilitySnapshotParams) (LiabilitySnapshot, error) {
	row := q.db.QueryRow(ctx, upsertLiabilitySnapshot,
		arg.ID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i LiabilitySnapshot
	err := row.Scan(
		&i.ID,
		&i.LiabilityID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
