// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: liability_snapshots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createLiabilitySnapshot = `-- name: CreateLiabilitySnapshot :one

WITH owned_liability AS (
    SELECT l.id AS lid
    FROM liabilities l
    WHERE l.id = $1 AND l.household_id = $8::uuid AND l.deleted_at IS NULL
)
INSERT INTO liability_snapshots (
    liability_id, year_month, amount, currency, as_of_date, description,
    created_by, updated_by
)
SELECT owned_liability.lid, $2, $3, $4, $5, $6, $7, $7
FROM owned_liability
RETURNING id, liability_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateLiabilitySnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	YearMonth   time.Time       `json:"year_month"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	HouseholdID uuid.UUID       `json:"household_id"`
}

// All snapshot queries verify the parent liability belongs to the requesting
// Household. This is belt + suspenders on top of the application-layer
// tenancy middleware: even if a handler forgets to filter, SQL will not
// expose or mutate snapshots from another Household.
func (q *Queries) CreateLiabilitySnapshot(ctx context.Context, arg CreateLiabilitySnapshotParams) (LiabilitySnapshot, error) {
	row := q.db.QueryRow(ctx, createLiabilitySnapshot,
		arg.ID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i LiabilitySnapshot
	err := row.Scan(
		&i.ID,
		&i.LiabilityID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLiabilityForImport = `-- name: GetLiabilityForImport :one
SELECT l.display_name, l.native_currency
FROM liabilities l
WHERE l.id = $1 AND l.household_id = $2 AND l.deleted_at IS NULL
`

type GetLiabilityForImportParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

type GetLiabilityForImportRow struct {
	DisplayName    string `json:"display_name"`
	NativeCurrency string `json:"native_currency"`
}

// GetLiabilityForImport returns the display name + native currency of an owned
// liability. Doubles as the ownership/existence check for the snapshot
// importer: ErrNoRows means the liability doesn't exist in this household (or
// is deleted), which the repo maps to ErrNotFound -> 404.
func (q *Queries) GetLiabilityForImport(ctx context.Context, arg GetLiabilityForImportParams) (GetLiabilityForImportRow, error) {
	row := q.db.QueryRow(ctx, getLiabilityForImport, arg.ID, arg.HouseholdID)
	var i GetLiabilityForImportRow
	err := row.Scan(&i.DisplayName, &i.NativeCurrency)
	return i, err
}

const getLiabilitySnapshotByID = `-- name: GetLiabilitySnapshotByID :one
SELECT s.id, s.liability_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM liability_snapshots s
JOIN liabilities l ON l.id = s.liability_id
WHERE s.id = $1
  AND l.household_id = $2
  AND l.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type GetLiabilitySnapshotByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetLiabilitySnapshotByID(ctx context.Context, arg GetLiabilitySnapshotByIDParams) (LiabilitySnapshot, error) {
	row := q.db.QueryRow(ctx, getLiabilitySnapshotByID, arg.ID, arg.HouseholdID)
	var i LiabilitySnapshot
	err := row.Scan(
		&i.ID,
		&i.LiabilityID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLatestLiabilitySnapshotsByLiabilityIDs = `-- name: ListLatestLiabilitySnapshotsByLiabilityIDs :many
SELECT DISTINCT ON (liability_id) id, liability_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
FROM liability_snapshots
WHERE liability_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY liability_id, year_month DESC
`

// Batch fetch of the most-recent snapshot per liability, for list views.
func (q *Queries) ListLatestLiabilitySnapshotsByLiabilityIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]LiabilitySnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestLiabilitySnapshotsByLiabilityIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiabilitySnapshot
	for rows.Next() {
		var i LiabilitySnapshot
		if err := rows.Scan(
			&i.ID,
			&i.LiabilityID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiabilitySnapshotsByLiabilityIDs = `-- name: ListLiabilitySnapshotsByLiabilityIDs :many
SELECT id, liability_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
FROM liability_snapshots
WHERE liability_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY liability_id, year_month
`

// Full ascending value series per liability, for the Liabilities Home time
// graphs (epic #204). Ascending order is what LiabilityTimeSeries' carry-
// forward sampling relies on; mirrors ListAssetSnapshotsByAssetIDs.
func (q *Queries) ListLiabilitySnapshotsByLiabilityIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]LiabilitySnapshot, error) {
	rows, err := q.db.Query(ctx, listLiabilitySnapshotsByLiabilityIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiabilitySnapshot
	for rows.Next() {
		var i LiabilitySnapshot
		if err := rows.Scan(
			&i.ID,
			&i.LiabilityID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiabilitySnapshotsForLiability = `-- name: ListLiabilitySnapshotsForLiability :many
SELECT s.id, s.liability_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM liability_snapshots s
JOIN liabilities l ON l.id = s.liability_id
WHERE s.liability_id = $1
  AND l.household_id = $2
  AND l.deleted_at IS NULL
  AND s.deleted_at IS NULL
ORDER BY s.year_month DESC
`

type ListLiabilitySnapshotsForLiabilityParams struct {
	LiabilityID uuid.UUID `json:"liability_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ListLiabilitySnapshotsForLiability(ctx context.Context, arg ListLiabilitySnapshotsForLiabilityParams) ([]LiabilitySnapshot, error) {
	rows, err := q.db.Query(ctx, listLiabilitySnapshotsForLiability, arg.LiabilityID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiabilitySnapshot
	for rows.Next() {
		var i LiabilitySnapshot
		if err := rows.Scan(
			&i.ID,
			&i.LiabilityID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLiabilitySnapshot = `-- name: SoftDeleteLiabilitySnapshot :execrows
UPDATE liability_snapshots s
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
FROM liabilities l
WHERE s.id = $1
  AND s.liability_id = l.id
  AND l.household_id = $2
  AND l.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type SoftDeleteLiabilitySnapshotParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteLiabilitySnapshot(ctx context.Context, arg SoftDeleteLiabilitySnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteLiabilitySnapshot, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLiabilitySnapshot = `-- name: UpdateLiabilitySnapshot :one
UPDATE liability_snapshots s
SET amount      = $3,
    currency    = $4,
    as_of_date  = $5,
    description = $6,
    updated_by  = $7,
    updated_at  = now()
FROM liabilities l
WHERE s.id = $1
  AND s.liability_id = l.id
  AND l.household_id = $2
  AND l.deleted_at IS NULL
  AND s.deleted_at IS NULL
RETURNING s.id, s.liability_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
`

type UpdateLiabilitySnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	HouseholdID uuid.UUID       `json:"household_id"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	UpdatedBy   *uuid.UUID      `json:"updated_by"`
}

func (q *Queries) UpdateLiabilitySnapshot(ctx context.Context, arg UpdateLiabilitySnapshotParams) (LiabilitySnapshot, error) {
	row := q.db.QueryRow(ctx, updateLiabilitySnapshot,
		arg.ID,
		arg.HouseholdID,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.UpdatedBy,
	)
	var i LiabilitySnapshot
	err := row.Scan(
		&i.ID,
		&i.LiabilityID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertLiabilitySnapshot = `-- name: UpsertLiabilitySnapshot :one
WITH owned_liability AS (
    SELECT l.id AS lid
    FROM liabilities l
    WHERE l.id = $1 AND l.household_id = $8::uuid AND l.deleted_at IS NULL
)
INSERT INTO liability_snapshots (
    liability_id, year_month, amount, currency, as_of_date, description,
    created_by, updated_by
)
SELECT owned_liability.lid, $2, $3, $4, $5, $6, $7, $7
FROM owned_liability
ON CONFLICT (liability_id, year_month) WHERE deleted_at IS NULL
DO UPDATE SET
    amount      = EXCLUDED.amount,
    currency    = EXCLUDED.currency,
    as_of_date  = EXCLUDED.as_of_date,
    description = EXCLUDED.description,
    updated_by  = EXCLUDED.updated_by,
    updated_at  = now()
RETURNING id, liability_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
`

type UpsertLiabilitySnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	YearMonth   time.Time       `json:"year_month"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	HouseholdID uuid.UUID       `json:"household_id"`
}

// UpsertLiabilitySnapshot inserts a snapshot or, when one already exists for
// the (liability_id, year_month) pair, overwrites it (last-write-wins) — the
// importer needs idempotent re-runs of a multi-year backfill. ON CONFLICT
// targets the partial unique index, so its predicate (deleted_at IS NULL) is
// repeated. created_by is only set on insert; updated_by always.
func (q *Queries) UpsertLiabilitySnapshot(ctx context.Context, arg UpsertLiabilitySnapshotParams) (LiabilitySnapshot, error) {
	row := q.db.QueryRow(ctx, upsertLiabilitySnapshot,
		arg.ID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i LiabilitySnapshot
	err := row.Scan(
		&i.ID,
		&i.LiabilityID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
