// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: local_credentials.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getLocalCredentialByUserID = `-- name: GetLocalCredentialByUserID :one
SELECT user_id, password_hash, created_at, updated_at
FROM local_credentials
WHERE user_id = $1
`

func (q *Queries) GetLocalCredentialByUserID(ctx context.Context, userID uuid.UUID) (LocalCredential, error) {
	row := q.db.QueryRow(ctx, getLocalCredentialByUserID, userID)
	var i LocalCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLocalCredential = `-- name: UpsertLocalCredential :one
INSERT INTO local_credentials (user_id, password_hash)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET password_hash = EXCLUDED.password_hash,
    updated_at    = now()
RETURNING user_id, password_hash, created_at, updated_at
`

type UpsertLocalCredentialParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

// Create or replace a User's local password credential. The founder register
// creates the first one; reset/reactivation (later slices) replace it. Keyed on
// the user_id PK so a member never accumulates more than one local credential.
func (q *Queries) UpsertLocalCredential(ctx context.Context, arg UpsertLocalCredentialParams) (LocalCredential, error) {
	row := q.db.QueryRow(ctx, upsertLocalCredential, arg.UserID, arg.PasswordHash)
	var i LocalCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
