// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Asset struct {
	ID              uuid.UUID          `json:"id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	DisplayName     string             `json:"display_name"`
	Description     *string            `json:"description"`
	Subtype         string             `json:"subtype"`
	OwnershipType   string             `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID         `json:"sole_owner_user_id"`
	NativeCurrency  string             `json:"native_currency"`
	Status          string             `json:"status"`
	TerminatedAt    *time.Time         `json:"terminated_at"`
	TerminationNote *string            `json:"termination_note"`
	CreatedBy       *uuid.UUID         `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedBy       *uuid.UUID         `json:"updated_by"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	TagID           *uuid.UUID         `json:"tag_id"`
}

type AssetSnapshot struct {
	ID          uuid.UUID          `json:"id"`
	AssetID     uuid.UUID          `json:"asset_id"`
	YearMonth   time.Time          `json:"year_month"`
	Amount      decimal.Decimal    `json:"amount"`
	Currency    string             `json:"currency"`
	AsOfDate    *time.Time         `json:"as_of_date"`
	Description *string            `json:"description"`
	CreatedBy   *uuid.UUID         `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedBy   *uuid.UUID         `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type BankAccountDetail struct {
	AssetID       uuid.UUID `json:"asset_id"`
	BankName      string    `json:"bank_name"`
	AccountNumber string    `json:"account_number"`
	AccountType   string    `json:"account_type"`
}

type BondDetail struct {
	InvestmentID      uuid.UUID       `json:"investment_id"`
	BondType          string          `json:"bond_type"`
	Issuer            string          `json:"issuer"`
	CouponRate        decimal.Decimal `json:"coupon_rate"`
	CouponFrequency   string          `json:"coupon_frequency"`
	MaturityDate      time.Time       `json:"maturity_date"`
	SeriesCode        *string         `json:"series_code"`
	CouponDisposition string          `json:"coupon_disposition"`
}

type FxRate struct {
	ID          uuid.UUID          `json:"id"`
	HouseholdID uuid.UUID          `json:"household_id"`
	YearMonth   time.Time          `json:"year_month"`
	Currency    string             `json:"currency"`
	Rate        decimal.Decimal    `json:"rate"`
	CreatedBy   *uuid.UUID         `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedBy   *uuid.UUID         `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type GoldDetail struct {
	InvestmentID uuid.UUID       `json:"investment_id"`
	Form         string          `json:"form"`
	Purity       decimal.Decimal `json:"purity"`
}

type Household struct {
	ID                   uuid.UUID          `json:"id"`
	DisplayName          string             `json:"display_name"`
	ReportingCurrency    string             `json:"reporting_currency"`
	CreatedBy            *uuid.UUID         `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedBy            *uuid.UUID         `json:"updated_by"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	MultiCurrencyEnabled bool               `json:"multi_currency_enabled"`
}

type HouseholdInvitation struct {
	ID           uuid.UUID          `json:"id"`
	HouseholdID  uuid.UUID          `json:"household_id"`
	InvitedEmail string             `json:"invited_email"`
	Token        string             `json:"token"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
}

type Income struct {
	ID              uuid.UUID          `json:"id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	Date            time.Time          `json:"date"`
	Amount          decimal.Decimal    `json:"amount"`
	Currency        string             `json:"currency"`
	Category        string             `json:"category"`
	Description     *string            `json:"description"`
	OwnershipType   string             `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID         `json:"sole_owner_user_id"`
	CreatedBy       *uuid.UUID         `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedBy       *uuid.UUID         `json:"updated_by"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	Regularity      string             `json:"regularity"`
}

type Investment struct {
	ID                     uuid.UUID          `json:"id"`
	HouseholdID            uuid.UUID          `json:"household_id"`
	DisplayName            string             `json:"display_name"`
	Description            *string            `json:"description"`
	Subtype                string             `json:"subtype"`
	OwnershipType          string             `json:"ownership_type"`
	SoleOwnerUserID        *uuid.UUID         `json:"sole_owner_user_id"`
	NativeCurrency         string             `json:"native_currency"`
	Status                 string             `json:"status"`
	TerminatedAt           *time.Time         `json:"terminated_at"`
	TerminationNote        *string            `json:"termination_note"`
	CreatedBy              *uuid.UUID         `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedBy              *uuid.UUID         `json:"updated_by"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	RiskProfile            string             `json:"risk_profile"`
	RolledFromInvestmentID *uuid.UUID         `json:"rolled_from_investment_id"`
	TagID                  *uuid.UUID         `json:"tag_id"`
}

type InvestmentSnapshot struct {
	ID              uuid.UUID          `json:"id"`
	InvestmentID    uuid.UUID          `json:"investment_id"`
	YearMonth       time.Time          `json:"year_month"`
	Amount          decimal.Decimal    `json:"amount"`
	Currency        string             `json:"currency"`
	Quantity        *decimal.Decimal   `json:"quantity"`
	PricePerUnit    *decimal.Decimal   `json:"price_per_unit"`
	AccruedInterest *decimal.Decimal   `json:"accrued_interest"`
	AsOfDate        *time.Time         `json:"as_of_date"`
	Description     *string            `json:"description"`
	CreatedBy       *uuid.UUID         `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedBy       *uuid.UUID         `json:"updated_by"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type InvestmentTransaction struct {
	ID                   uuid.UUID          `json:"id"`
	InvestmentID         uuid.UUID          `json:"investment_id"`
	TransactionType      string             `json:"transaction_type"`
	TransactionDate      time.Time          `json:"transaction_date"`
	Currency             string             `json:"currency"`
	Description          *string            `json:"description"`
	Amount               *decimal.Decimal   `json:"amount"`
	Quantity             *decimal.Decimal   `json:"quantity"`
	PricePerUnit         *decimal.Decimal   `json:"price_per_unit"`
	PrincipalAmount      *decimal.Decimal   `json:"principal_amount"`
	InterestAmount       *decimal.Decimal   `json:"interest_amount"`
	PrincipalDisposition *string            `json:"principal_disposition"`
	InterestDisposition  *string            `json:"interest_disposition"`
	CreatedBy            *uuid.UUID         `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedBy            *uuid.UUID         `json:"updated_by"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type Liability struct {
	ID               uuid.UUID          `json:"id"`
	HouseholdID      uuid.UUID          `json:"household_id"`
	DisplayName      string             `json:"display_name"`
	Description      *string            `json:"description"`
	Subtype          string             `json:"subtype"`
	OwnershipType    string             `json:"ownership_type"`
	SoleOwnerUserID  *uuid.UUID         `json:"sole_owner_user_id"`
	NativeCurrency   string             `json:"native_currency"`
	Status           string             `json:"status"`
	TerminatedAt     *time.Time         `json:"terminated_at"`
	TerminationNote  *string            `json:"termination_note"`
	CounterpartyName string             `json:"counterparty_name"`
	Principal        *decimal.Decimal   `json:"principal"`
	InterestRate     *decimal.Decimal   `json:"interest_rate"`
	TermMonths       *int32             `json:"term_months"`
	StartDate        *time.Time         `json:"start_date"`
	MaturityDate     *time.Time         `json:"maturity_date"`
	CreatedBy        *uuid.UUID         `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedBy        *uuid.UUID         `json:"updated_by"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	TagID            *uuid.UUID         `json:"tag_id"`
}

type LiabilitySnapshot struct {
	ID          uuid.UUID          `json:"id"`
	LiabilityID uuid.UUID          `json:"liability_id"`
	YearMonth   time.Time          `json:"year_month"`
	Amount      decimal.Decimal    `json:"amount"`
	Currency    string             `json:"currency"`
	AsOfDate    *time.Time         `json:"as_of_date"`
	Description *string            `json:"description"`
	CreatedBy   *uuid.UUID         `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedBy   *uuid.UUID         `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type MonthlyReport struct {
	ID                          uuid.UUID          `json:"id"`
	HouseholdID                 uuid.UUID          `json:"household_id"`
	YearMonth                   time.Time          `json:"year_month"`
	GeneratedAt                 pgtype.Timestamptz `json:"generated_at"`
	NwTotal                     decimal.Decimal    `json:"nw_total"`
	NwAssets                    decimal.Decimal    `json:"nw_assets"`
	NwLiabilities               decimal.Decimal    `json:"nw_liabilities"`
	NwReceivables               decimal.Decimal    `json:"nw_receivables"`
	NwInvestments               decimal.Decimal    `json:"nw_investments"`
	EarnedIncomeTotal           *decimal.Decimal   `json:"earned_income_total"`
	EarnedIncomeSalary          *decimal.Decimal   `json:"earned_income_salary"`
	EarnedIncomeBusiness        *decimal.Decimal   `json:"earned_income_business"`
	EarnedIncomeRental          *decimal.Decimal   `json:"earned_income_rental"`
	EarnedIncomeGift            *decimal.Decimal   `json:"earned_income_gift"`
	EarnedIncomeTaxRefund       *decimal.Decimal   `json:"earned_income_tax_refund"`
	EarnedIncomeInsurance       *decimal.Decimal   `json:"earned_income_insurance"`
	EarnedIncomeOther           *decimal.Decimal   `json:"earned_income_other"`
	InvestmentReturnTotal       *decimal.Decimal   `json:"investment_return_total"`
	InvestmentReturnStock       *decimal.Decimal   `json:"investment_return_stock"`
	InvestmentReturnMutualFund  *decimal.Decimal   `json:"investment_return_mutual_fund"`
	InvestmentReturnBond        *decimal.Decimal   `json:"investment_return_bond"`
	InvestmentReturnGold        *decimal.Decimal   `json:"investment_return_gold"`
	InvestmentReturnTimeDeposit *decimal.Decimal   `json:"investment_return_time_deposit"`
	AssetValueChange            *decimal.Decimal   `json:"asset_value_change"`
	DerivedLivingExpenses       *decimal.Decimal   `json:"derived_living_expenses"`
	UserBreakdowns              []byte             `json:"user_breakdowns"`
	FxRatesUsed                 []byte             `json:"fx_rates_used"`
	StalePositions              []byte             `json:"stale_positions"`
	MissingFx                   []byte             `json:"missing_fx"`
}

type MutualFundDetail struct {
	InvestmentID uuid.UUID `json:"investment_id"`
	FundCode     string    `json:"fund_code"`
	FundManager  *string   `json:"fund_manager"`
	FundType     string    `json:"fund_type"`
}

type OnboardingHandshake struct {
	ID               string             `json:"id"`
	GoogleSub        string             `json:"google_sub"`
	Email            string             `json:"email"`
	DisplayName      string             `json:"display_name"`
	PictureUrl       *string            `json:"picture_url"`
	SeedLocale       string             `json:"seed_locale"`
	HintInvitationID *uuid.UUID         `json:"hint_invitation_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type PropertyDetail struct {
	AssetID                uuid.UUID        `json:"asset_id"`
	PropertyType           string           `json:"property_type"`
	Address                *string          `json:"address"`
	AcquisitionDate        *time.Time       `json:"acquisition_date"`
	AcquisitionCost        *decimal.Decimal `json:"acquisition_cost"`
	AnnualAppreciationRate *decimal.Decimal `json:"annual_appreciation_rate"`
}

type Receivable struct {
	ID               uuid.UUID          `json:"id"`
	HouseholdID      uuid.UUID          `json:"household_id"`
	DisplayName      string             `json:"display_name"`
	Description      *string            `json:"description"`
	OwnershipType    string             `json:"ownership_type"`
	SoleOwnerUserID  *uuid.UUID         `json:"sole_owner_user_id"`
	NativeCurrency   string             `json:"native_currency"`
	Status           string             `json:"status"`
	TerminatedAt     *time.Time         `json:"terminated_at"`
	TerminationNote  *string            `json:"termination_note"`
	CounterpartyName string             `json:"counterparty_name"`
	DueDate          *time.Time         `json:"due_date"`
	CreatedBy        *uuid.UUID         `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedBy        *uuid.UUID         `json:"updated_by"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	TagID            *uuid.UUID         `json:"tag_id"`
}

type ReceivableSnapshot struct {
	ID           uuid.UUID          `json:"id"`
	ReceivableID uuid.UUID          `json:"receivable_id"`
	YearMonth    time.Time          `json:"year_month"`
	Amount       decimal.Decimal    `json:"amount"`
	Currency     string             `json:"currency"`
	AsOfDate     *time.Time         `json:"as_of_date"`
	Description  *string            `json:"description"`
	CreatedBy    *uuid.UUID         `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedBy    *uuid.UUID         `json:"updated_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Session struct {
	ID         string             `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	UserAgent  *string            `json:"user_agent"`
}

type StockDetail struct {
	InvestmentID uuid.UUID `json:"investment_id"`
	Ticker       string    `json:"ticker"`
	Exchange     string    `json:"exchange"`
}

type Tag struct {
	ID          uuid.UUID          `json:"id"`
	HouseholdID uuid.UUID          `json:"household_id"`
	Name        string             `json:"name"`
	Color       string             `json:"color"`
	CreatedBy   *uuid.UUID         `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedBy   *uuid.UUID         `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type TimeDepositDetail struct {
	InvestmentID   uuid.UUID       `json:"investment_id"`
	BankName       string          `json:"bank_name"`
	Principal      decimal.Decimal `json:"principal"`
	InterestRate   decimal.Decimal `json:"interest_rate"`
	TermMonths     int32           `json:"term_months"`
	PlacementDate  time.Time       `json:"placement_date"`
	MaturityDate   time.Time       `json:"maturity_date"`
	RolloverPolicy string          `json:"rollover_policy"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	HouseholdID       uuid.UUID          `json:"household_id"`
	DisplayName       string             `json:"display_name"`
	Email             string             `json:"email"`
	GoogleSub         string             `json:"google_sub"`
	Locale            string             `json:"locale"`
	TimeZone          string             `json:"time_zone"`
	CreatedBy         *uuid.UUID         `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedBy         *uuid.UUID         `json:"updated_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	Nickname          *string            `json:"nickname"`
	PictureUrl        *string            `json:"picture_url"`
	Theme             string             `json:"theme"`
	CarryoverDateMode string             `json:"carryover_date_mode"`
}

type VehicleDetail struct {
	AssetID                uuid.UUID        `json:"asset_id"`
	VehicleType            string           `json:"vehicle_type"`
	Make                   *string          `json:"make"`
	Model                  *string          `json:"model"`
	Year                   *int32           `json:"year"`
	PlateNumber            *string          `json:"plate_number"`
	AnnualDepreciationRate *decimal.Decimal `json:"annual_depreciation_rate"`
}
