// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monthly_reports.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const deleteMonthlyReportsOutsideRange = `-- name: DeleteMonthlyReportsOutsideRange :exec
DELETE FROM monthly_reports
WHERE household_id = $1 AND (year_month < $2 OR year_month > $3)
`

type DeleteMonthlyReportsOutsideRangeParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	YearMonth   time.Time `json:"year_month"`
	YearMonth_2 time.Time `json:"year_month_2"`
}

// Drop cache rows for months no longer in range (e.g. the earliest snapshots
// were deleted, shrinking the report window). Keeps the materialized set in
// sync with the engine's month range on regeneration.
func (q *Queries) DeleteMonthlyReportsOutsideRange(ctx context.Context, arg DeleteMonthlyReportsOutsideRangeParams) error {
	_, err := q.db.Exec(ctx, deleteMonthlyReportsOutsideRange, arg.HouseholdID, arg.YearMonth, arg.YearMonth_2)
	return err
}

const getMonthlyReport = `-- name: GetMonthlyReport :one
SELECT id, household_id, year_month, generated_at, nw_total, nw_assets, nw_liabilities, nw_receivables, nw_investments, earned_income_total, earned_income_salary, earned_income_business, earned_income_rental, earned_income_gift, earned_income_tax_refund, earned_income_insurance, earned_income_other, investment_return_total, investment_return_stock, investment_return_mutual_fund, investment_return_bond, investment_return_gold, investment_return_time_deposit, asset_value_change, derived_living_expenses, user_breakdowns, fx_rates_used, stale_positions, missing_fx
FROM monthly_reports
WHERE household_id = $1 AND year_month = $2
`

type GetMonthlyReportParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	YearMonth   time.Time `json:"year_month"`
}

func (q *Queries) GetMonthlyReport(ctx context.Context, arg GetMonthlyReportParams) (MonthlyReport, error) {
	row := q.db.QueryRow(ctx, getMonthlyReport, arg.HouseholdID, arg.YearMonth)
	var i MonthlyReport
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.YearMonth,
		&i.GeneratedAt,
		&i.NwTotal,
		&i.NwAssets,
		&i.NwLiabilities,
		&i.NwReceivables,
		&i.NwInvestments,
		&i.EarnedIncomeTotal,
		&i.EarnedIncomeSalary,
		&i.EarnedIncomeBusiness,
		&i.EarnedIncomeRental,
		&i.EarnedIncomeGift,
		&i.EarnedIncomeTaxRefund,
		&i.EarnedIncomeInsurance,
		&i.EarnedIncomeOther,
		&i.InvestmentReturnTotal,
		&i.InvestmentReturnStock,
		&i.InvestmentReturnMutualFund,
		&i.InvestmentReturnBond,
		&i.InvestmentReturnGold,
		&i.InvestmentReturnTimeDeposit,
		&i.AssetValueChange,
		&i.DerivedLivingExpenses,
		&i.UserBreakdowns,
		&i.FxRatesUsed,
		&i.StalePositions,
		&i.MissingFx,
	)
	return i, err
}

const listAssetSnapshotsForReport = `-- name: ListAssetSnapshotsForReport :many

SELECT s.asset_id AS position_id, s.year_month, s.amount, s.currency
FROM asset_snapshots s
JOIN assets a ON a.id = s.asset_id
WHERE a.household_id = $1 AND a.deleted_at IS NULL AND s.deleted_at IS NULL
ORDER BY s.asset_id, s.year_month
`

type ListAssetSnapshotsForReportRow struct {
	PositionID uuid.UUID       `json:"position_id"`
	YearMonth  time.Time       `json:"year_month"`
	Amount     decimal.Decimal `json:"amount"`
	Currency   string          `json:"currency"`
}

// ----- engine inputs: flat snapshots (position_id, year_month, amount) -----
// All non-deleted snapshots for the household, ordered for the engine's
// per-position carry-forward scan.
func (q *Queries) ListAssetSnapshotsForReport(ctx context.Context, householdID uuid.UUID) ([]ListAssetSnapshotsForReportRow, error) {
	rows, err := q.db.Query(ctx, listAssetSnapshotsForReport, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetSnapshotsForReportRow
	for rows.Next() {
		var i ListAssetSnapshotsForReportRow
		if err := rows.Scan(
			&i.PositionID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsForReport = `-- name: ListAssetsForReport :many

SELECT id, display_name, subtype, ownership_type, sole_owner_user_id, terminated_at
FROM assets
WHERE household_id = $1 AND deleted_at IS NULL
`

type ListAssetsForReportRow struct {
	ID              uuid.UUID  `json:"id"`
	DisplayName     string     `json:"display_name"`
	Subtype         string     `json:"subtype"`
	OwnershipType   string     `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID `json:"sole_owner_user_id"`
	TerminatedAt    *time.Time `json:"terminated_at"`
}

// ----- engine inputs: positions (lifecycle + ownership) -------------------
// terminated_at NULL => active (biconditional CHECK, migration 00012); the
// engine needs only terminated_at for month-granular lifecycle suppression
// plus ownership for the per-user / Joint breakdown.
// display_name + subtype let the report name unrecorded positions in the
// dashboard drill-down (issue #50): the stale-position list carries enough to
// render a label and deep-link to the position's detail page.
func (q *Queries) ListAssetsForReport(ctx context.Context, householdID uuid.UUID) ([]ListAssetsForReportRow, error) {
	rows, err := q.db.Query(ctx, listAssetsForReport, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsForReportRow
	for rows.Next() {
		var i ListAssetsForReportRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Subtype,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
			&i.TerminatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFxRatesForReport = `-- name: ListFxRatesForReport :many
SELECT currency, year_month, rate
FROM fx_rates
WHERE household_id = $1 AND deleted_at IS NULL
ORDER BY currency, year_month
`

type ListFxRatesForReportRow struct {
	Currency  string          `json:"currency"`
	YearMonth time.Time       `json:"year_month"`
	Rate      decimal.Decimal `json:"rate"`
}

// All non-deleted FX rates for the household; the engine indexes them by
// currency and applies the latest with year_month <= M (carry-forward).
func (q *Queries) ListFxRatesForReport(ctx context.Context, householdID uuid.UUID) ([]ListFxRatesForReportRow, error) {
	rows, err := q.db.Query(ctx, listFxRatesForReport, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFxRatesForReportRow
	for rows.Next() {
		var i ListFxRatesForReportRow
		if err := rows.Scan(&i.Currency, &i.YearMonth, &i.Rate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeForReport = `-- name: ListIncomeForReport :many

SELECT date, amount, currency, category, ownership_type, sole_owner_user_id
FROM income
WHERE household_id = $1 AND deleted_at IS NULL
`

type ListIncomeForReportRow struct {
	Date            time.Time       `json:"date"`
	Amount          decimal.Decimal `json:"amount"`
	Currency        string          `json:"currency"`
	Category        string          `json:"category"`
	OwnershipType   string          `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID      `json:"sole_owner_user_id"`
}

// ----- engine inputs: income + investment transactions (slice 2) ----------
func (q *Queries) ListIncomeForReport(ctx context.Context, householdID uuid.UUID) ([]ListIncomeForReportRow, error) {
	rows, err := q.db.Query(ctx, listIncomeForReport, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncomeForReportRow
	for rows.Next() {
		var i ListIncomeForReportRow
		if err := rows.Scan(
			&i.Date,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentSnapshotsForReport = `-- name: ListInvestmentSnapshotsForReport :many
SELECT s.investment_id AS position_id, s.year_month, s.amount, s.currency
FROM investment_snapshots s
JOIN investments i ON i.id = s.investment_id
WHERE i.household_id = $1 AND i.deleted_at IS NULL AND s.deleted_at IS NULL
ORDER BY s.investment_id, s.year_month
`

type ListInvestmentSnapshotsForReportRow struct {
	PositionID uuid.UUID       `json:"position_id"`
	YearMonth  time.Time       `json:"year_month"`
	Amount     decimal.Decimal `json:"amount"`
	Currency   string          `json:"currency"`
}

func (q *Queries) ListInvestmentSnapshotsForReport(ctx context.Context, householdID uuid.UUID) ([]ListInvestmentSnapshotsForReportRow, error) {
	rows, err := q.db.Query(ctx, listInvestmentSnapshotsForReport, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvestmentSnapshotsForReportRow
	for rows.Next() {
		var i ListInvestmentSnapshotsForReportRow
		if err := rows.Scan(
			&i.PositionID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentTransactionsForReport = `-- name: ListInvestmentTransactionsForReport :many
SELECT t.investment_id, t.transaction_date, t.transaction_type, t.currency,
       t.amount, t.quantity,
       t.principal_amount, t.interest_amount,
       t.principal_disposition, t.interest_disposition
FROM investment_transactions t
JOIN investments i ON i.id = t.investment_id
WHERE i.household_id = $1 AND i.deleted_at IS NULL AND t.deleted_at IS NULL
ORDER BY t.investment_id, t.transaction_date
`

type ListInvestmentTransactionsForReportRow struct {
	InvestmentID         uuid.UUID        `json:"investment_id"`
	TransactionDate      time.Time        `json:"transaction_date"`
	TransactionType      string           `json:"transaction_type"`
	Currency             string           `json:"currency"`
	Amount               *decimal.Decimal `json:"amount"`
	Quantity             *decimal.Decimal `json:"quantity"`
	PrincipalAmount      *decimal.Decimal `json:"principal_amount"`
	InterestAmount       *decimal.Decimal `json:"interest_amount"`
	PrincipalDisposition *string          `json:"principal_disposition"`
	InterestDisposition  *string          `json:"interest_disposition"`
}

// Transaction cash-flow fields the engine maps to cash_in/cash_out (ADR-0008).
// price_per_unit is omitted — it doesn't enter the return formula.
func (q *Queries) ListInvestmentTransactionsForReport(ctx context.Context, householdID uuid.UUID) ([]ListInvestmentTransactionsForReportRow, error) {
	rows, err := q.db.Query(ctx, listInvestmentTransactionsForReport, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvestmentTransactionsForReportRow
	for rows.Next() {
		var i ListInvestmentTransactionsForReportRow
		if err := rows.Scan(
			&i.InvestmentID,
			&i.TransactionDate,
			&i.TransactionType,
			&i.Currency,
			&i.Amount,
			&i.Quantity,
			&i.PrincipalAmount,
			&i.InterestAmount,
			&i.PrincipalDisposition,
			&i.InterestDisposition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentsForReport = `-- name: ListInvestmentsForReport :many
SELECT i.id, i.display_name, i.subtype, i.ownership_type, i.sole_owner_user_id, i.terminated_at,
       i.native_currency, i.rolled_from_investment_id,
       td.principal AS td_principal, td.placement_date AS td_placement_date
FROM investments i
LEFT JOIN time_deposit_details td ON td.investment_id = i.id
WHERE i.household_id = $1 AND i.deleted_at IS NULL
`

type ListInvestmentsForReportRow struct {
	ID                     uuid.UUID        `json:"id"`
	DisplayName            string           `json:"display_name"`
	Subtype                string           `json:"subtype"`
	OwnershipType          string           `json:"ownership_type"`
	SoleOwnerUserID        *uuid.UUID       `json:"sole_owner_user_id"`
	TerminatedAt           *time.Time       `json:"terminated_at"`
	NativeCurrency         string           `json:"native_currency"`
	RolledFromInvestmentID *uuid.UUID       `json:"rolled_from_investment_id"`
	TdPrincipal            *decimal.Decimal `json:"td_principal"`
	TdPlacementDate        *time.Time       `json:"td_placement_date"`
}

// native_currency + the time_deposit placement fields let the engine synthesize
// a placement cash_in for TDs (issue #27): a TD records no Buy, so without it
// the placement-month snapshot 0→principal reads as pure return. td.principal /
// td.placement_date are NULL for non-TD subtypes.
func (q *Queries) ListInvestmentsForReport(ctx context.Context, householdID uuid.UUID) ([]ListInvestmentsForReportRow, error) {
	rows, err := q.db.Query(ctx, listInvestmentsForReport, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvestmentsForReportRow
	for rows.Next() {
		var i ListInvestmentsForReportRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Subtype,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
			&i.TerminatedAt,
			&i.NativeCurrency,
			&i.RolledFromInvestmentID,
			&i.TdPrincipal,
			&i.TdPlacementDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiabilitiesForReport = `-- name: ListLiabilitiesForReport :many
SELECT id, display_name, subtype, ownership_type, sole_owner_user_id, terminated_at
FROM liabilities
WHERE household_id = $1 AND deleted_at IS NULL
`

type ListLiabilitiesForReportRow struct {
	ID              uuid.UUID  `json:"id"`
	DisplayName     string     `json:"display_name"`
	Subtype         string     `json:"subtype"`
	OwnershipType   string     `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID `json:"sole_owner_user_id"`
	TerminatedAt    *time.Time `json:"terminated_at"`
}

func (q *Queries) ListLiabilitiesForReport(ctx context.Context, householdID uuid.UUID) ([]ListLiabilitiesForReportRow, error) {
	rows, err := q.db.Query(ctx, listLiabilitiesForReport, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiabilitiesForReportRow
	for rows.Next() {
		var i ListLiabilitiesForReportRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Subtype,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
			&i.TerminatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiabilitySnapshotsForReport = `-- name: ListLiabilitySnapshotsForReport :many
SELECT s.liability_id AS position_id, s.year_month, s.amount, s.currency
FROM liability_snapshots s
JOIN liabilities l ON l.id = s.liability_id
WHERE l.household_id = $1 AND l.deleted_at IS NULL AND s.deleted_at IS NULL
ORDER BY s.liability_id, s.year_month
`

type ListLiabilitySnapshotsForReportRow struct {
	PositionID uuid.UUID       `json:"position_id"`
	YearMonth  time.Time       `json:"year_month"`
	Amount     decimal.Decimal `json:"amount"`
	Currency   string          `json:"currency"`
}

func (q *Queries) ListLiabilitySnapshotsForReport(ctx context.Context, householdID uuid.UUID) ([]ListLiabilitySnapshotsForReportRow, error) {
	rows, err := q.db.Query(ctx, listLiabilitySnapshotsForReport, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiabilitySnapshotsForReportRow
	for rows.Next() {
		var i ListLiabilitySnapshotsForReportRow
		if err := rows.Scan(
			&i.PositionID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlyReports = `-- name: ListMonthlyReports :many

SELECT id, household_id, year_month, generated_at, nw_total, nw_assets, nw_liabilities, nw_receivables, nw_investments, earned_income_total, earned_income_salary, earned_income_business, earned_income_rental, earned_income_gift, earned_income_tax_refund, earned_income_insurance, earned_income_other, investment_return_total, investment_return_stock, investment_return_mutual_fund, investment_return_bond, investment_return_gold, investment_return_time_deposit, asset_value_change, derived_living_expenses, user_breakdowns, fx_rates_used, stale_positions, missing_fx
FROM monthly_reports
WHERE household_id = $1
ORDER BY year_month
`

// Materialized monthly net-worth reports (ADR-0006 / ADR-0012).
//
// The report row is a regenerable cache keyed by (household_id, year_month);
// UpsertMonthlyReport writes in place on regeneration. The *ForReport queries
// below feed the pure engine in internal/repo (monthly_reports_engine.go):
// one lightweight position fetch + one flat snapshot fetch per group, from
// which the engine derives every month with carry-forward in Go.
//
// Slice-1 scope: only the net-worth columns + user_breakdowns + stale_positions
// are written; the income-statement columns and fx JSON land in M5 slices 2-3.
func (q *Queries) ListMonthlyReports(ctx context.Context, householdID uuid.UUID) ([]MonthlyReport, error) {
	rows, err := q.db.Query(ctx, listMonthlyReports, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyReport
	for rows.Next() {
		var i MonthlyReport
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.YearMonth,
			&i.GeneratedAt,
			&i.NwTotal,
			&i.NwAssets,
			&i.NwLiabilities,
			&i.NwReceivables,
			&i.NwInvestments,
			&i.EarnedIncomeTotal,
			&i.EarnedIncomeSalary,
			&i.EarnedIncomeBusiness,
			&i.EarnedIncomeRental,
			&i.EarnedIncomeGift,
			&i.EarnedIncomeTaxRefund,
			&i.EarnedIncomeInsurance,
			&i.EarnedIncomeOther,
			&i.InvestmentReturnTotal,
			&i.InvestmentReturnStock,
			&i.InvestmentReturnMutualFund,
			&i.InvestmentReturnBond,
			&i.InvestmentReturnGold,
			&i.InvestmentReturnTimeDeposit,
			&i.AssetValueChange,
			&i.DerivedLivingExpenses,
			&i.UserBreakdowns,
			&i.FxRatesUsed,
			&i.StalePositions,
			&i.MissingFx,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivableSnapshotsForReport = `-- name: ListReceivableSnapshotsForReport :many
SELECT s.receivable_id AS position_id, s.year_month, s.amount, s.currency
FROM receivable_snapshots s
JOIN receivables rc ON rc.id = s.receivable_id
WHERE rc.household_id = $1 AND rc.deleted_at IS NULL AND s.deleted_at IS NULL
ORDER BY s.receivable_id, s.year_month
`

type ListReceivableSnapshotsForReportRow struct {
	PositionID uuid.UUID       `json:"position_id"`
	YearMonth  time.Time       `json:"year_month"`
	Amount     decimal.Decimal `json:"amount"`
	Currency   string          `json:"currency"`
}

func (q *Queries) ListReceivableSnapshotsForReport(ctx context.Context, householdID uuid.UUID) ([]ListReceivableSnapshotsForReportRow, error) {
	rows, err := q.db.Query(ctx, listReceivableSnapshotsForReport, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivableSnapshotsForReportRow
	for rows.Next() {
		var i ListReceivableSnapshotsForReportRow
		if err := rows.Scan(
			&i.PositionID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivablesForReport = `-- name: ListReceivablesForReport :many
SELECT id, display_name, ownership_type, sole_owner_user_id, terminated_at
FROM receivables
WHERE household_id = $1 AND deleted_at IS NULL
`

type ListReceivablesForReportRow struct {
	ID              uuid.UUID  `json:"id"`
	DisplayName     string     `json:"display_name"`
	OwnershipType   string     `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID `json:"sole_owner_user_id"`
	TerminatedAt    *time.Time `json:"terminated_at"`
}

func (q *Queries) ListReceivablesForReport(ctx context.Context, householdID uuid.UUID) ([]ListReceivablesForReportRow, error) {
	rows, err := q.db.Query(ctx, listReceivablesForReport, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivablesForReportRow
	for rows.Next() {
		var i ListReceivablesForReportRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
			&i.TerminatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxReportInputUpdatedAt = `-- name: MaxReportInputUpdatedAt :one
SELECT COALESCE(GREATEST(
    (SELECT MAX(s.updated_at) FROM asset_snapshots s
        JOIN assets a ON a.id = s.asset_id
        WHERE a.household_id = $1 AND s.year_month <= $2),
    (SELECT MAX(s.updated_at) FROM liability_snapshots s
        JOIN liabilities l ON l.id = s.liability_id
        WHERE l.household_id = $1 AND s.year_month <= $2),
    (SELECT MAX(s.updated_at) FROM receivable_snapshots s
        JOIN receivables rc ON rc.id = s.receivable_id
        WHERE rc.household_id = $1 AND s.year_month <= $2),
    (SELECT MAX(s.updated_at) FROM investment_snapshots s
        JOIN investments i ON i.id = s.investment_id
        WHERE i.household_id = $1 AND s.year_month <= $2),
    (SELECT MAX(updated_at) FROM income
        WHERE household_id = $1 AND date <= $2),
    (SELECT MAX(t.updated_at) FROM investment_transactions t
        JOIN investments i ON i.id = t.investment_id
        WHERE i.household_id = $1 AND t.transaction_date <= $2),
    (SELECT MAX(updated_at) FROM fx_rates
        WHERE household_id = $1 AND year_month <= $2),
    (SELECT MAX(updated_at) FROM assets       WHERE household_id = $1),
    (SELECT MAX(updated_at) FROM liabilities  WHERE household_id = $1),
    (SELECT MAX(updated_at) FROM receivables  WHERE household_id = $1),
    (SELECT MAX(updated_at) FROM investments  WHERE household_id = $1),
    (SELECT MAX(updated_at) FROM households   WHERE id = $1)
), to_timestamp(0))::timestamptz AS max_updated_at
`

type MaxReportInputUpdatedAtParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	YearMonth   time.Time `json:"year_month"`
}

// Staleness watermark: the newest updated_at across every input that feeds
// month <= $2 for household $1 (ADR-0006 conservative <=M rule). A report row
// is stale when its generated_at predates this value. Snapshot subqueries do
// not filter deleted_at so soft-deletes count; parent tables are household-wide
// (metadata is timeless). Detail tables and `users` are deliberately excluded
// (ADR-0006). Income + investment_transactions joined the set in slice 2;
// fx_rates in slice 3.
func (q *Queries) MaxReportInputUpdatedAt(ctx context.Context, arg MaxReportInputUpdatedAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, maxReportInputUpdatedAt, arg.HouseholdID, arg.YearMonth)
	var max_updated_at pgtype.Timestamptz
	err := row.Scan(&max_updated_at)
	return max_updated_at, err
}

const upsertMonthlyReport = `-- name: UpsertMonthlyReport :one
INSERT INTO monthly_reports (
    household_id, year_month, generated_at,
    nw_total, nw_assets, nw_liabilities, nw_receivables, nw_investments,
    earned_income_total, earned_income_salary, earned_income_business,
    earned_income_rental, earned_income_gift, earned_income_tax_refund,
    earned_income_insurance, earned_income_other,
    investment_return_total, investment_return_stock, investment_return_mutual_fund,
    investment_return_bond, investment_return_gold, investment_return_time_deposit,
    asset_value_change, derived_living_expenses,
    user_breakdowns, stale_positions, fx_rates_used, missing_fx
) VALUES (
    $1, $2, now(),
    $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21,
    $22, $23,
    $24, $25, $26, $27
)
ON CONFLICT (household_id, year_month) DO UPDATE SET
    generated_at                   = now(),
    nw_total                       = EXCLUDED.nw_total,
    nw_assets                      = EXCLUDED.nw_assets,
    nw_liabilities                 = EXCLUDED.nw_liabilities,
    nw_receivables                 = EXCLUDED.nw_receivables,
    nw_investments                 = EXCLUDED.nw_investments,
    earned_income_total            = EXCLUDED.earned_income_total,
    earned_income_salary           = EXCLUDED.earned_income_salary,
    earned_income_business         = EXCLUDED.earned_income_business,
    earned_income_rental           = EXCLUDED.earned_income_rental,
    earned_income_gift             = EXCLUDED.earned_income_gift,
    earned_income_tax_refund       = EXCLUDED.earned_income_tax_refund,
    earned_income_insurance        = EXCLUDED.earned_income_insurance,
    earned_income_other            = EXCLUDED.earned_income_other,
    investment_return_total        = EXCLUDED.investment_return_total,
    investment_return_stock        = EXCLUDED.investment_return_stock,
    investment_return_mutual_fund  = EXCLUDED.investment_return_mutual_fund,
    investment_return_bond         = EXCLUDED.investment_return_bond,
    investment_return_gold         = EXCLUDED.investment_return_gold,
    investment_return_time_deposit = EXCLUDED.investment_return_time_deposit,
    asset_value_change             = EXCLUDED.asset_value_change,
    derived_living_expenses        = EXCLUDED.derived_living_expenses,
    user_breakdowns                = EXCLUDED.user_breakdowns,
    stale_positions                = EXCLUDED.stale_positions,
    fx_rates_used                  = EXCLUDED.fx_rates_used,
    missing_fx                     = EXCLUDED.missing_fx
RETURNING id, household_id, year_month, generated_at, nw_total, nw_assets, nw_liabilities, nw_receivables, nw_investments, earned_income_total, earned_income_salary, earned_income_business, earned_income_rental, earned_income_gift, earned_income_tax_refund, earned_income_insurance, earned_income_other, investment_return_total, investment_return_stock, investment_return_mutual_fund, investment_return_bond, investment_return_gold, investment_return_time_deposit, asset_value_change, derived_living_expenses, user_breakdowns, fx_rates_used, stale_positions, missing_fx
`

type UpsertMonthlyReportParams struct {
	HouseholdID                 uuid.UUID        `json:"household_id"`
	YearMonth                   time.Time        `json:"year_month"`
	NwTotal                     decimal.Decimal  `json:"nw_total"`
	NwAssets                    decimal.Decimal  `json:"nw_assets"`
	NwLiabilities               decimal.Decimal  `json:"nw_liabilities"`
	NwReceivables               decimal.Decimal  `json:"nw_receivables"`
	NwInvestments               decimal.Decimal  `json:"nw_investments"`
	EarnedIncomeTotal           *decimal.Decimal `json:"earned_income_total"`
	EarnedIncomeSalary          *decimal.Decimal `json:"earned_income_salary"`
	EarnedIncomeBusiness        *decimal.Decimal `json:"earned_income_business"`
	EarnedIncomeRental          *decimal.Decimal `json:"earned_income_rental"`
	EarnedIncomeGift            *decimal.Decimal `json:"earned_income_gift"`
	EarnedIncomeTaxRefund       *decimal.Decimal `json:"earned_income_tax_refund"`
	EarnedIncomeInsurance       *decimal.Decimal `json:"earned_income_insurance"`
	EarnedIncomeOther           *decimal.Decimal `json:"earned_income_other"`
	InvestmentReturnTotal       *decimal.Decimal `json:"investment_return_total"`
	InvestmentReturnStock       *decimal.Decimal `json:"investment_return_stock"`
	InvestmentReturnMutualFund  *decimal.Decimal `json:"investment_return_mutual_fund"`
	InvestmentReturnBond        *decimal.Decimal `json:"investment_return_bond"`
	InvestmentReturnGold        *decimal.Decimal `json:"investment_return_gold"`
	InvestmentReturnTimeDeposit *decimal.Decimal `json:"investment_return_time_deposit"`
	AssetValueChange            *decimal.Decimal `json:"asset_value_change"`
	DerivedLivingExpenses       *decimal.Decimal `json:"derived_living_expenses"`
	UserBreakdowns              []byte           `json:"user_breakdowns"`
	StalePositions              []byte           `json:"stale_positions"`
	FxRatesUsed                 []byte           `json:"fx_rates_used"`
	MissingFx                   []byte           `json:"missing_fx"`
}

func (q *Queries) UpsertMonthlyReport(ctx context.Context, arg UpsertMonthlyReportParams) (MonthlyReport, error) {
	row := q.db.QueryRow(ctx, upsertMonthlyReport,
		arg.HouseholdID,
		arg.YearMonth,
		arg.NwTotal,
		arg.NwAssets,
		arg.NwLiabilities,
		arg.NwReceivables,
		arg.NwInvestments,
		arg.EarnedIncomeTotal,
		arg.EarnedIncomeSalary,
		arg.EarnedIncomeBusiness,
		arg.EarnedIncomeRental,
		arg.EarnedIncomeGift,
		arg.EarnedIncomeTaxRefund,
		arg.EarnedIncomeInsurance,
		arg.EarnedIncomeOther,
		arg.InvestmentReturnTotal,
		arg.InvestmentReturnStock,
		arg.InvestmentReturnMutualFund,
		arg.InvestmentReturnBond,
		arg.InvestmentReturnGold,
		arg.InvestmentReturnTimeDeposit,
		arg.AssetValueChange,
		arg.DerivedLivingExpenses,
		arg.UserBreakdowns,
		arg.StalePositions,
		arg.FxRatesUsed,
		arg.MissingFx,
	)
	var i MonthlyReport
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.YearMonth,
		&i.GeneratedAt,
		&i.NwTotal,
		&i.NwAssets,
		&i.NwLiabilities,
		&i.NwReceivables,
		&i.NwInvestments,
		&i.EarnedIncomeTotal,
		&i.EarnedIncomeSalary,
		&i.EarnedIncomeBusiness,
		&i.EarnedIncomeRental,
		&i.EarnedIncomeGift,
		&i.EarnedIncomeTaxRefund,
		&i.EarnedIncomeInsurance,
		&i.EarnedIncomeOther,
		&i.InvestmentReturnTotal,
		&i.InvestmentReturnStock,
		&i.InvestmentReturnMutualFund,
		&i.InvestmentReturnBond,
		&i.InvestmentReturnGold,
		&i.InvestmentReturnTimeDeposit,
		&i.AssetValueChange,
		&i.DerivedLivingExpenses,
		&i.UserBreakdowns,
		&i.FxRatesUsed,
		&i.StalePositions,
		&i.MissingFx,
	)
	return i, err
}
