// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: onboarding_handshakes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOnboardingHandshake = `-- name: CreateOnboardingHandshake :one
INSERT INTO onboarding_handshakes (
    id, google_sub, email, display_name, picture_url, seed_locale, hint_invitation_id, password_hash, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, google_sub, email, display_name, picture_url, seed_locale, hint_invitation_id, created_at, expires_at, password_hash
`

type CreateOnboardingHandshakeParams struct {
	ID               string             `json:"id"`
	GoogleSub        *string            `json:"google_sub"`
	Email            string             `json:"email"`
	DisplayName      string             `json:"display_name"`
	PictureUrl       *string            `json:"picture_url"`
	SeedLocale       string             `json:"seed_locale"`
	HintInvitationID *uuid.UUID         `json:"hint_invitation_id"`
	PasswordHash     *string            `json:"password_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOnboardingHandshake(ctx context.Context, arg CreateOnboardingHandshakeParams) (OnboardingHandshake, error) {
	row := q.db.QueryRow(ctx, createOnboardingHandshake,
		arg.ID,
		arg.GoogleSub,
		arg.Email,
		arg.DisplayName,
		arg.PictureUrl,
		arg.SeedLocale,
		arg.HintInvitationID,
		arg.PasswordHash,
		arg.ExpiresAt,
	)
	var i OnboardingHandshake
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.DisplayName,
		&i.PictureUrl,
		&i.SeedLocale,
		&i.HintInvitationID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PasswordHash,
	)
	return i, err
}

const deleteExpiredOnboardingHandshakes = `-- name: DeleteExpiredOnboardingHandshakes :exec
DELETE FROM onboarding_handshakes WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredOnboardingHandshakes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOnboardingHandshakes)
	return err
}

const deleteOnboardingHandshake = `-- name: DeleteOnboardingHandshake :exec
DELETE FROM onboarding_handshakes WHERE id = $1
`

func (q *Queries) DeleteOnboardingHandshake(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOnboardingHandshake, id)
	return err
}

const getOnboardingHandshake = `-- name: GetOnboardingHandshake :one
SELECT id, google_sub, email, display_name, picture_url, seed_locale, hint_invitation_id, created_at, expires_at, password_hash
FROM onboarding_handshakes
WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetOnboardingHandshake(ctx context.Context, id string) (OnboardingHandshake, error) {
	row := q.db.QueryRow(ctx, getOnboardingHandshake, id)
	var i OnboardingHandshake
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.DisplayName,
		&i.PictureUrl,
		&i.SeedLocale,
		&i.HintInvitationID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PasswordHash,
	)
	return i, err
}
