// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET used_at = now()
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
RETURNING token_hash, user_id, created_at, expires_at, used_at
`

// Single-use atomic consume for the emailed reset (#282): marks the token used
// iff it is still unused AND unexpired, returning the row. A consumed / expired
// token matches zero rows (pgx.ErrNoRows), so a reset link works exactly once —
// the guard is the WHERE, not a prior read. Mirrors ConsumeInvitationByTokenHash.
func (q *Queries) ConsumePasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (
    token_hash, user_id, expires_at
) VALUES (
    $1, $2, $3
)
RETURNING token_hash, user_id, created_at, expires_at, used_at
`

type CreatePasswordResetTokenParams struct {
	TokenHash string             `json:"token_hash"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// token_hash is the SHA-256 of a ≥256-bit random token (#281/#282, ADR-0039);
// the plaintext lives only in the emailed link, never at rest.
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens WHERE expires_at <= now()
`

// Housekeeping sweep of spent windows, mirroring DeleteExpiredSessions /
// DeleteExpiredOnboardingHandshakes.
func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const deletePasswordResetTokensForUser = `-- name: DeletePasswordResetTokensForUser :exec
DELETE FROM password_reset_tokens WHERE user_id = $1
`

// Invalidate a user's outstanding reset tokens. Called after a successful reset
// so a second still-valid link (e.g. a double request) can't be replayed once
// one has set the password.
func (q *Queries) DeletePasswordResetTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordResetTokensForUser, userID)
	return err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT token_hash, user_id, created_at, expires_at, used_at
FROM password_reset_tokens
WHERE token_hash = $1
`

// Read-only resolve by hashed token for the reset-set screen's preview, which
// validates the link without consuming it (so a reload doesn't burn the
// single-use token). The atomic consume is ConsumePasswordResetToken.
func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}
