// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receivable_snapshots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createReceivableSnapshot = `-- name: CreateReceivableSnapshot :one

WITH owned_receivable AS (
    SELECT r.id AS rid
    FROM receivables r
    WHERE r.id = $1 AND r.household_id = $8::uuid AND r.deleted_at IS NULL
)
INSERT INTO receivable_snapshots (
    receivable_id, year_month, amount, currency, as_of_date, description,
    created_by, updated_by
)
SELECT owned_receivable.rid, $2, $3, $4, $5, $6, $7, $7
FROM owned_receivable
RETURNING id, receivable_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateReceivableSnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	YearMonth   time.Time       `json:"year_month"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	HouseholdID uuid.UUID       `json:"household_id"`
}

// All snapshot queries verify the parent receivable belongs to the requesting
// Household. This is belt + suspenders on top of the application-layer
// tenancy middleware: even if a handler forgets to filter, SQL will not
// expose or mutate snapshots from another Household.
func (q *Queries) CreateReceivableSnapshot(ctx context.Context, arg CreateReceivableSnapshotParams) (ReceivableSnapshot, error) {
	row := q.db.QueryRow(ctx, createReceivableSnapshot,
		arg.ID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i ReceivableSnapshot
	err := row.Scan(
		&i.ID,
		&i.ReceivableID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReceivableForImport = `-- name: GetReceivableForImport :one
SELECT r.display_name, r.native_currency
FROM receivables r
WHERE r.id = $1 AND r.household_id = $2 AND r.deleted_at IS NULL
`

type GetReceivableForImportParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

type GetReceivableForImportRow struct {
	DisplayName    string `json:"display_name"`
	NativeCurrency string `json:"native_currency"`
}

// GetReceivableForImport returns the display name + native currency of an
// owned receivable. Doubles as the ownership/existence check for the snapshot
// importer: ErrNoRows means the receivable doesn't exist in this household (or
// is deleted), which the repo maps to ErrNotFound -> 404.
func (q *Queries) GetReceivableForImport(ctx context.Context, arg GetReceivableForImportParams) (GetReceivableForImportRow, error) {
	row := q.db.QueryRow(ctx, getReceivableForImport, arg.ID, arg.HouseholdID)
	var i GetReceivableForImportRow
	err := row.Scan(&i.DisplayName, &i.NativeCurrency)
	return i, err
}

const getReceivableSnapshotByID = `-- name: GetReceivableSnapshotByID :one
SELECT s.id, s.receivable_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM receivable_snapshots s
JOIN receivables r ON r.id = s.receivable_id
WHERE s.id = $1
  AND r.household_id = $2
  AND r.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type GetReceivableSnapshotByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetReceivableSnapshotByID(ctx context.Context, arg GetReceivableSnapshotByIDParams) (ReceivableSnapshot, error) {
	row := q.db.QueryRow(ctx, getReceivableSnapshotByID, arg.ID, arg.HouseholdID)
	var i ReceivableSnapshot
	err := row.Scan(
		&i.ID,
		&i.ReceivableID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLatestReceivableSnapshotsByReceivableIDs = `-- name: ListLatestReceivableSnapshotsByReceivableIDs :many
SELECT DISTINCT ON (receivable_id) id, receivable_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
FROM receivable_snapshots
WHERE receivable_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY receivable_id, year_month DESC
`

// Batch fetch of the most-recent snapshot per receivable, for list views.
func (q *Queries) ListLatestReceivableSnapshotsByReceivableIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ReceivableSnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestReceivableSnapshotsByReceivableIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceivableSnapshot
	for rows.Next() {
		var i ReceivableSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ReceivableID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivableSnapshotsByReceivableIDs = `-- name: ListReceivableSnapshotsByReceivableIDs :many
SELECT id, receivable_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
FROM receivable_snapshots
WHERE receivable_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY receivable_id, year_month
`

// Full ascending value series per receivable, for the Receivables list
// total-over-time chart (epic #204). Ascending order is what
// ReceivableTimeSeries' carry-forward sampling relies on; mirrors
// ListAssetSnapshotsByAssetIDs.
func (q *Queries) ListReceivableSnapshotsByReceivableIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ReceivableSnapshot, error) {
	rows, err := q.db.Query(ctx, listReceivableSnapshotsByReceivableIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceivableSnapshot
	for rows.Next() {
		var i ReceivableSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ReceivableID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivableSnapshotsForReceivable = `-- name: ListReceivableSnapshotsForReceivable :many
SELECT s.id, s.receivable_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM receivable_snapshots s
JOIN receivables r ON r.id = s.receivable_id
WHERE s.receivable_id = $1
  AND r.household_id = $2
  AND r.deleted_at IS NULL
  AND s.deleted_at IS NULL
ORDER BY s.year_month DESC
`

type ListReceivableSnapshotsForReceivableParams struct {
	ReceivableID uuid.UUID `json:"receivable_id"`
	HouseholdID  uuid.UUID `json:"household_id"`
}

func (q *Queries) ListReceivableSnapshotsForReceivable(ctx context.Context, arg ListReceivableSnapshotsForReceivableParams) ([]ReceivableSnapshot, error) {
	rows, err := q.db.Query(ctx, listReceivableSnapshotsForReceivable, arg.ReceivableID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceivableSnapshot
	for rows.Next() {
		var i ReceivableSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ReceivableID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteReceivableSnapshot = `-- name: SoftDeleteReceivableSnapshot :execrows
UPDATE receivable_snapshots s
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
FROM receivables r
WHERE s.id = $1
  AND s.receivable_id = r.id
  AND r.household_id = $2
  AND r.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type SoftDeleteReceivableSnapshotParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteReceivableSnapshot(ctx context.Context, arg SoftDeleteReceivableSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteReceivableSnapshot, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReceivableSnapshot = `-- name: UpdateReceivableSnapshot :one
UPDATE receivable_snapshots s
SET amount      = $3,
    currency    = $4,
    as_of_date  = $5,
    description = $6,
    updated_by  = $7,
    updated_at  = now()
FROM receivables r
WHERE s.id = $1
  AND s.receivable_id = r.id
  AND r.household_id = $2
  AND r.deleted_at IS NULL
  AND s.deleted_at IS NULL
RETURNING s.id, s.receivable_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
`

type UpdateReceivableSnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	HouseholdID uuid.UUID       `json:"household_id"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	UpdatedBy   *uuid.UUID      `json:"updated_by"`
}

func (q *Queries) UpdateReceivableSnapshot(ctx context.Context, arg UpdateReceivableSnapshotParams) (ReceivableSnapshot, error) {
	row := q.db.QueryRow(ctx, updateReceivableSnapshot,
		arg.ID,
		arg.HouseholdID,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.UpdatedBy,
	)
	var i ReceivableSnapshot
	err := row.Scan(
		&i.ID,
		&i.ReceivableID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertReceivableSnapshot = `-- name: UpsertReceivableSnapshot :one
WITH owned_receivable AS (
    SELECT r.id AS rid
    FROM receivables r
    WHERE r.id = $1 AND r.household_id = $8::uuid AND r.deleted_at IS NULL
)
INSERT INTO receivable_snapshots (
    receivable_id, year_month, amount, currency, as_of_date, description,
    created_by, updated_by
)
SELECT owned_receivable.rid, $2, $3, $4, $5, $6, $7, $7
FROM owned_receivable
ON CONFLICT (receivable_id, year_month) WHERE deleted_at IS NULL
DO UPDATE SET
    amount      = EXCLUDED.amount,
    currency    = EXCLUDED.currency,
    as_of_date  = EXCLUDED.as_of_date,
    description = EXCLUDED.description,
    updated_by  = EXCLUDED.updated_by,
    updated_at  = now()
RETURNING id, receivable_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
`

type UpsertReceivableSnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	YearMonth   time.Time       `json:"year_month"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	HouseholdID uuid.UUID       `json:"household_id"`
}

// UpsertReceivableSnapshot inserts a snapshot or, when one already exists for
// the (receivable_id, year_month) pair, overwrites it (last-write-wins) — the
// importer needs idempotent re-runs of a multi-year backfill. ON CONFLICT
// targets the partial unique index, so its predicate (deleted_at IS NULL) is
// repeated. created_by is only set on insert; updated_by always.
func (q *Queries) UpsertReceivableSnapshot(ctx context.Context, arg UpsertReceivableSnapshotParams) (ReceivableSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertReceivableSnapshot,
		arg.ID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i ReceivableSnapshot
	err := row.Scan(
		&i.ID,
		&i.ReceivableID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
