// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receivables.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createReceivable = `-- name: CreateReceivable :one
INSERT INTO receivables (
    household_id, display_name, description,
    ownership_type, sole_owner_user_id, native_currency,
    counterparty_name, due_date,
    created_by, updated_by, entry_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $9, $10
)
RETURNING id, household_id, display_name, description, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, counterparty_name, due_date, created_by, created_at, updated_by, updated_at, deleted_at, tag_id, entry_type
`

type CreateReceivableParams struct {
	HouseholdID      uuid.UUID  `json:"household_id"`
	DisplayName      string     `json:"display_name"`
	Description      *string    `json:"description"`
	OwnershipType    string     `json:"ownership_type"`
	SoleOwnerUserID  *uuid.UUID `json:"sole_owner_user_id"`
	NativeCurrency   string     `json:"native_currency"`
	CounterpartyName string     `json:"counterparty_name"`
	DueDate          *time.Time `json:"due_date"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	EntryType        string     `json:"entry_type"`
}

func (q *Queries) CreateReceivable(ctx context.Context, arg CreateReceivableParams) (Receivable, error) {
	row := q.db.QueryRow(ctx, createReceivable,
		arg.HouseholdID,
		arg.DisplayName,
		arg.Description,
		arg.OwnershipType,
		arg.SoleOwnerUserID,
		arg.NativeCurrency,
		arg.CounterpartyName,
		arg.DueDate,
		arg.CreatedBy,
		arg.EntryType,
	)
	var i Receivable
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Description,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.NativeCurrency,
		&i.Status,
		&i.TerminatedAt,
		&i.TerminationNote,
		&i.CounterpartyName,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TagID,
		&i.EntryType,
	)
	return i, err
}

const getReceivableByID = `-- name: GetReceivableByID :one
SELECT id, household_id, display_name, description, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, counterparty_name, due_date, created_by, created_at, updated_by, updated_at, deleted_at, tag_id, entry_type
FROM receivables
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetReceivableByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetReceivableByID(ctx context.Context, arg GetReceivableByIDParams) (Receivable, error) {
	row := q.db.QueryRow(ctx, getReceivableByID, arg.ID, arg.HouseholdID)
	var i Receivable
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Description,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.NativeCurrency,
		&i.Status,
		&i.TerminatedAt,
		&i.TerminationNote,
		&i.CounterpartyName,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TagID,
		&i.EntryType,
	)
	return i, err
}

const listReceivablesByHousehold = `-- name: ListReceivablesByHousehold :many
SELECT id, household_id, display_name, description, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, counterparty_name, due_date, created_by, created_at, updated_by, updated_at, deleted_at, tag_id, entry_type
FROM receivables
WHERE household_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListReceivablesByHousehold(ctx context.Context, householdID uuid.UUID) ([]Receivable, error) {
	rows, err := q.db.Query(ctx, listReceivablesByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receivable
	for rows.Next() {
		var i Receivable
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.DisplayName,
			&i.Description,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
			&i.NativeCurrency,
			&i.Status,
			&i.TerminatedAt,
			&i.TerminationNote,
			&i.CounterpartyName,
			&i.DueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TagID,
			&i.EntryType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteReceivable = `-- name: SoftDeleteReceivable :execrows
UPDATE receivables
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type SoftDeleteReceivableParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteReceivable(ctx context.Context, arg SoftDeleteReceivableParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteReceivable, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReceivable = `-- name: UpdateReceivable :one
UPDATE receivables
SET display_name       = $3,
    description        = $4,
    ownership_type     = $5,
    sole_owner_user_id = $6,
    counterparty_name  = $7,
    due_date           = $8,
    updated_by         = $9,
    -- Editable after the fact — the only remedy for a mis-declared birth
    -- (ADR-0053 §3); see the note on UpdateAsset for why COALESCE.
    entry_type         = COALESCE($10::text, entry_type),
    updated_at         = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING id, household_id, display_name, description, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, counterparty_name, due_date, created_by, created_at, updated_by, updated_at, deleted_at, tag_id, entry_type
`

type UpdateReceivableParams struct {
	ID               uuid.UUID  `json:"id"`
	HouseholdID      uuid.UUID  `json:"household_id"`
	DisplayName      string     `json:"display_name"`
	Description      *string    `json:"description"`
	OwnershipType    string     `json:"ownership_type"`
	SoleOwnerUserID  *uuid.UUID `json:"sole_owner_user_id"`
	CounterpartyName string     `json:"counterparty_name"`
	DueDate          *time.Time `json:"due_date"`
	UpdatedBy        *uuid.UUID `json:"updated_by"`
	EntryType        *string    `json:"entry_type"`
}

func (q *Queries) UpdateReceivable(ctx context.Context, arg UpdateReceivableParams) (Receivable, error) {
	row := q.db.QueryRow(ctx, updateReceivable,
		arg.ID,
		arg.HouseholdID,
		arg.DisplayName,
		arg.Description,
		arg.OwnershipType,
		arg.SoleOwnerUserID,
		arg.CounterpartyName,
		arg.DueDate,
		arg.UpdatedBy,
		arg.EntryType,
	)
	var i Receivable
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Description,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.NativeCurrency,
		&i.Status,
		&i.TerminatedAt,
		&i.TerminationNote,
		&i.CounterpartyName,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TagID,
		&i.EntryType,
	)
	return i, err
}

const updateReceivableLifecycle = `-- name: UpdateReceivableLifecycle :one
UPDATE receivables
SET status           = $3,
    terminated_at    = $4,
    termination_note = $5,
    updated_by       = $6,
    updated_at       = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING id, household_id, display_name, description, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, counterparty_name, due_date, created_by, created_at, updated_by, updated_at, deleted_at, tag_id, entry_type
`

type UpdateReceivableLifecycleParams struct {
	ID              uuid.UUID  `json:"id"`
	HouseholdID     uuid.UUID  `json:"household_id"`
	Status          string     `json:"status"`
	TerminatedAt    *time.Time `json:"terminated_at"`
	TerminationNote *string    `json:"termination_note"`
	UpdatedBy       *uuid.UUID `json:"updated_by"`
}

func (q *Queries) UpdateReceivableLifecycle(ctx context.Context, arg UpdateReceivableLifecycleParams) (Receivable, error) {
	row := q.db.QueryRow(ctx, updateReceivableLifecycle,
		arg.ID,
		arg.HouseholdID,
		arg.Status,
		arg.TerminatedAt,
		arg.TerminationNote,
		arg.UpdatedBy,
	)
	var i Receivable
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Description,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.NativeCurrency,
		&i.Status,
		&i.TerminatedAt,
		&i.TerminationNote,
		&i.CounterpartyName,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TagID,
		&i.EntryType,
	)
	return i, err
}
