// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receivable_snapshots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const cascadeSoftDeleteReceivableSnapshots = `-- name: CascadeSoftDeleteReceivableSnapshots :execrows
UPDATE receivable_snapshots s
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
FROM receivables r
WHERE s.receivable_id = $1
  AND s.receivable_id = r.id
  AND r.household_id = $2
  AND r.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type CascadeSoftDeleteReceivableSnapshotsParams struct {
	ReceivableID uuid.UUID  `json:"receivable_id"`
	HouseholdID  uuid.UUID  `json:"household_id"`
	UpdatedBy    *uuid.UUID `json:"updated_by"`
}

// CascadeSoftDeleteReceivableSnapshots tombstones every live snapshot of one
// receivable — see CascadeSoftDeleteAssetSnapshots for the ordering contract
// and why the already-deleted child is left alone (INV-SOFT-DELETE-05).
func (q *Queries) CascadeSoftDeleteReceivableSnapshots(ctx context.Context, arg CascadeSoftDeleteReceivableSnapshotsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cascadeSoftDeleteReceivableSnapshots, arg.ReceivableID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createReceivableSnapshot = `-- name: CreateReceivableSnapshot :one

WITH owned_receivable AS (
    SELECT r.id AS rid
    FROM receivables r
    WHERE r.id = $1 AND r.household_id = $8::uuid AND r.deleted_at IS NULL
)
INSERT INTO receivable_snapshots (
    receivable_id, year_month, amount, currency, as_of_date, description,
    created_by, updated_by
)
SELECT owned_receivable.rid, $2, $3, $4, $5, $6, $7, $7
FROM owned_receivable
RETURNING id, receivable_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateReceivableSnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	YearMonth   time.Time       `json:"year_month"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	HouseholdID uuid.UUID       `json:"household_id"`
}

// All snapshot queries verify the parent receivable belongs to the requesting
// Household. This is belt + suspenders on top of the application-layer
// tenancy middleware: even if a handler forgets to filter, SQL will not
// expose or mutate snapshots from another Household.
func (q *Queries) CreateReceivableSnapshot(ctx context.Context, arg CreateReceivableSnapshotParams) (ReceivableSnapshot, error) {
	row := q.db.QueryRow(ctx, createReceivableSnapshot,
		arg.ID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i ReceivableSnapshot
	err := row.Scan(
		&i.ID,
		&i.ReceivableID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArchivedReceivableSnapshotAtMonth = `-- name: GetArchivedReceivableSnapshotAtMonth :one
SELECT s.id, s.receivable_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM receivable_snapshots s
JOIN receivables rc ON rc.id = s.receivable_id
WHERE s.receivable_id = $1
  AND s.year_month = $2::date
  AND rc.household_id = $3::uuid
  AND rc.deleted_at IS NULL
  AND s.deleted_at = $4::timestamptz
  AND s.amount <> 0
ORDER BY s.created_at DESC
LIMIT 1
`

type GetArchivedReceivableSnapshotAtMonthParams struct {
	ReceivableID uuid.UUID          `json:"receivable_id"`
	YearMonth    time.Time          `json:"year_month"`
	HouseholdID  uuid.UUID          `json:"household_id"`
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) GetArchivedReceivableSnapshotAtMonth(ctx context.Context, arg GetArchivedReceivableSnapshotAtMonthParams) (ReceivableSnapshot, error) {
	row := q.db.QueryRow(ctx, getArchivedReceivableSnapshotAtMonth,
		arg.ReceivableID,
		arg.YearMonth,
		arg.HouseholdID,
		arg.ArchivedAt,
	)
	var i ReceivableSnapshot
	err := row.Scan(
		&i.ID,
		&i.ReceivableID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReceivableForImport = `-- name: GetReceivableForImport :one
SELECT r.display_name, r.native_currency
FROM receivables r
WHERE r.id = $1 AND r.household_id = $2 AND r.deleted_at IS NULL
`

type GetReceivableForImportParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

type GetReceivableForImportRow struct {
	DisplayName    string `json:"display_name"`
	NativeCurrency string `json:"native_currency"`
}

// GetReceivableForImport returns the display name + native currency of an
// owned receivable. Doubles as the ownership/existence check for the snapshot
// importer: ErrNoRows means the receivable doesn't exist in this household (or
// is deleted), which the repo maps to ErrNotFound -> 404.
func (q *Queries) GetReceivableForImport(ctx context.Context, arg GetReceivableForImportParams) (GetReceivableForImportRow, error) {
	row := q.db.QueryRow(ctx, getReceivableForImport, arg.ID, arg.HouseholdID)
	var i GetReceivableForImportRow
	err := row.Scan(&i.DisplayName, &i.NativeCurrency)
	return i, err
}

const getReceivableSnapshotAtMonth = `-- name: GetReceivableSnapshotAtMonth :one

SELECT s.id, s.receivable_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM receivable_snapshots s
JOIN receivables rc ON rc.id = s.receivable_id
WHERE s.receivable_id = $1
  AND s.year_month = $2::date
  AND rc.household_id = $3::uuid
  AND rc.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type GetReceivableSnapshotAtMonthParams struct {
	ReceivableID uuid.UUID `json:"receivable_id"`
	YearMonth    time.Time `json:"year_month"`
	HouseholdID  uuid.UUID `json:"household_id"`
}

// Close-snapshot displacement (ADR-0052 §2) — see asset_snapshots.sql for the
// mechanism and the reasoning behind each guard.
func (q *Queries) GetReceivableSnapshotAtMonth(ctx context.Context, arg GetReceivableSnapshotAtMonthParams) (ReceivableSnapshot, error) {
	row := q.db.QueryRow(ctx, getReceivableSnapshotAtMonth, arg.ReceivableID, arg.YearMonth, arg.HouseholdID)
	var i ReceivableSnapshot
	err := row.Scan(
		&i.ID,
		&i.ReceivableID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReceivableSnapshotByID = `-- name: GetReceivableSnapshotByID :one
SELECT s.id, s.receivable_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM receivable_snapshots s
JOIN receivables r ON r.id = s.receivable_id
WHERE s.id = $1
  AND r.household_id = $2
  AND r.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type GetReceivableSnapshotByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetReceivableSnapshotByID(ctx context.Context, arg GetReceivableSnapshotByIDParams) (ReceivableSnapshot, error) {
	row := q.db.QueryRow(ctx, getReceivableSnapshotByID, arg.ID, arg.HouseholdID)
	var i ReceivableSnapshot
	err := row.Scan(
		&i.ID,
		&i.ReceivableID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEligibleReceivableIDsForMonth = `-- name: ListEligibleReceivableIDsForMonth :many
SELECT id
FROM receivables
WHERE household_id = $1::uuid
  AND deleted_at IS NULL
  AND (terminated_at IS NULL OR terminated_at >= $2::date)
`

type ListEligibleReceivableIDsForMonthParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	YearMonth   time.Time `json:"year_month"`
}

// ListEligibleReceivableIDsForMonth returns the ids of the household's
// receivables that may legitimately hold a snapshot for the given target month
// (ADR-0046 month-aware eligibility): owned, not deleted, and either still
// active or terminated in the target month or later. A receivable terminated
// *before* the target month never appears — its forward contribution is already
// frozen by the carry-forward rule. No created_at guard, for the same reason as
// the Asset entry list: created_at is a record timestamp, not economic
// existence, and gating on it would block legitimate backfill/onboarding.
func (q *Queries) ListEligibleReceivableIDsForMonth(ctx context.Context, arg ListEligibleReceivableIDsForMonthParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEligibleReceivableIDsForMonth, arg.HouseholdID, arg.YearMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleReceivablesForMonth = `-- name: ListEligibleReceivablesForMonth :many
SELECT id, display_name, native_currency, ownership_type, sole_owner_user_id
FROM receivables
WHERE household_id = $1::uuid
  AND deleted_at IS NULL
  AND (terminated_at IS NULL OR terminated_at >= $2::date)
ORDER BY display_name
`

type ListEligibleReceivablesForMonthParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	YearMonth   time.Time `json:"year_month"`
}

type ListEligibleReceivablesForMonthRow struct {
	ID              uuid.UUID  `json:"id"`
	DisplayName     string     `json:"display_name"`
	NativeCurrency  string     `json:"native_currency"`
	OwnershipType   string     `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID `json:"sole_owner_user_id"`
}

// ListEligibleReceivablesForMonth is ListEligibleReceivableIDsForMonth plus the
// display fields the bulk monthly-entry list needs (ADR-0046): name and native
// currency. Receivables are a flat group with no subtype, so the entry view
// renders one ungrouped list; rows are ordered by display name.
func (q *Queries) ListEligibleReceivablesForMonth(ctx context.Context, arg ListEligibleReceivablesForMonthParams) ([]ListEligibleReceivablesForMonthRow, error) {
	rows, err := q.db.Query(ctx, listEligibleReceivablesForMonth, arg.HouseholdID, arg.YearMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleReceivablesForMonthRow
	for rows.Next() {
		var i ListEligibleReceivablesForMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.NativeCurrency,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestReceivableSnapshotsByReceivableIDs = `-- name: ListLatestReceivableSnapshotsByReceivableIDs :many
SELECT DISTINCT ON (receivable_id) id, receivable_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
FROM receivable_snapshots
WHERE receivable_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY receivable_id, year_month DESC
`

// Batch fetch of the most-recent snapshot per receivable, for list views.
func (q *Queries) ListLatestReceivableSnapshotsByReceivableIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ReceivableSnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestReceivableSnapshotsByReceivableIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceivableSnapshot
	for rows.Next() {
		var i ReceivableSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ReceivableID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestSnapshotsByReceivableIDsAsOfMonth = `-- name: ListLatestSnapshotsByReceivableIDsAsOfMonth :many
SELECT DISTINCT ON (receivable_id) receivable_id, amount, year_month
FROM receivable_snapshots
WHERE receivable_id = ANY($1::uuid[])
  AND deleted_at IS NULL
  AND year_month <= $2::date
ORDER BY receivable_id, year_month DESC
`

type ListLatestSnapshotsByReceivableIDsAsOfMonthParams struct {
	ReceivableIds []uuid.UUID `json:"receivable_ids"`
	YearMonth     time.Time   `json:"year_month"`
}

type ListLatestSnapshotsByReceivableIDsAsOfMonthRow struct {
	ReceivableID uuid.UUID       `json:"receivable_id"`
	Amount       decimal.Decimal `json:"amount"`
	YearMonth    time.Time       `json:"year_month"`
}

// ListLatestSnapshotsByReceivableIDsAsOfMonth returns, per receivable, the
// most-recent snapshot at or before the target month — the carry-forward
// prefill for the entry list. Month-bounded so a value entered ahead of the
// target does not leak backwards as the prefill.
func (q *Queries) ListLatestSnapshotsByReceivableIDsAsOfMonth(ctx context.Context, arg ListLatestSnapshotsByReceivableIDsAsOfMonthParams) ([]ListLatestSnapshotsByReceivableIDsAsOfMonthRow, error) {
	rows, err := q.db.Query(ctx, listLatestSnapshotsByReceivableIDsAsOfMonth, arg.ReceivableIds, arg.YearMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestSnapshotsByReceivableIDsAsOfMonthRow
	for rows.Next() {
		var i ListLatestSnapshotsByReceivableIDsAsOfMonthRow
		if err := rows.Scan(&i.ReceivableID, &i.Amount, &i.YearMonth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivableSnapshotsByReceivableIDs = `-- name: ListReceivableSnapshotsByReceivableIDs :many
SELECT id, receivable_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
FROM receivable_snapshots
WHERE receivable_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY receivable_id, year_month
`

// Full ascending value series per receivable, for the Receivables list
// total-over-time chart (epic #204). Ascending order is what
// ReceivableTimeSeries' carry-forward sampling relies on; mirrors
// ListAssetSnapshotsByAssetIDs.
func (q *Queries) ListReceivableSnapshotsByReceivableIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ReceivableSnapshot, error) {
	rows, err := q.db.Query(ctx, listReceivableSnapshotsByReceivableIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceivableSnapshot
	for rows.Next() {
		var i ReceivableSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ReceivableID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivableSnapshotsForReceivable = `-- name: ListReceivableSnapshotsForReceivable :many
SELECT s.id, s.receivable_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM receivable_snapshots s
JOIN receivables r ON r.id = s.receivable_id
WHERE s.receivable_id = $1
  AND r.household_id = $2
  AND r.deleted_at IS NULL
  AND s.deleted_at IS NULL
ORDER BY s.year_month DESC
`

type ListReceivableSnapshotsForReceivableParams struct {
	ReceivableID uuid.UUID `json:"receivable_id"`
	HouseholdID  uuid.UUID `json:"household_id"`
}

func (q *Queries) ListReceivableSnapshotsForReceivable(ctx context.Context, arg ListReceivableSnapshotsForReceivableParams) ([]ReceivableSnapshot, error) {
	rows, err := q.db.Query(ctx, listReceivableSnapshotsForReceivable, arg.ReceivableID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceivableSnapshot
	for rows.Next() {
		var i ReceivableSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ReceivableID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreReceivableSnapshot = `-- name: RestoreReceivableSnapshot :execrows
UPDATE receivable_snapshots s
SET deleted_at = NULL,
    updated_by = $1,
    updated_at = now()
FROM receivables rc
WHERE s.id = $2
  AND s.receivable_id = rc.id
  AND rc.household_id = $3::uuid
  AND rc.deleted_at IS NULL
  AND s.deleted_at IS NOT NULL
`

type RestoreReceivableSnapshotParams struct {
	UpdatedBy   *uuid.UUID `json:"updated_by"`
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
}

func (q *Queries) RestoreReceivableSnapshot(ctx context.Context, arg RestoreReceivableSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreReceivableSnapshot, arg.UpdatedBy, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteReceivableSnapshot = `-- name: SoftDeleteReceivableSnapshot :execrows
UPDATE receivable_snapshots s
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
FROM receivables r
WHERE s.id = $1
  AND s.receivable_id = r.id
  AND r.household_id = $2
  AND r.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type SoftDeleteReceivableSnapshotParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteReceivableSnapshot(ctx context.Context, arg SoftDeleteReceivableSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteReceivableSnapshot, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReceivableSnapshot = `-- name: UpdateReceivableSnapshot :one
UPDATE receivable_snapshots s
SET amount      = $3,
    currency    = $4,
    as_of_date  = $5,
    description = $6,
    updated_by  = $7,
    updated_at  = now()
FROM receivables r
WHERE s.id = $1
  AND s.receivable_id = r.id
  AND r.household_id = $2
  AND r.deleted_at IS NULL
  AND s.deleted_at IS NULL
RETURNING s.id, s.receivable_id, s.year_month, s.amount, s.currency, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
`

type UpdateReceivableSnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	HouseholdID uuid.UUID       `json:"household_id"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	UpdatedBy   *uuid.UUID      `json:"updated_by"`
}

func (q *Queries) UpdateReceivableSnapshot(ctx context.Context, arg UpdateReceivableSnapshotParams) (ReceivableSnapshot, error) {
	row := q.db.QueryRow(ctx, updateReceivableSnapshot,
		arg.ID,
		arg.HouseholdID,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.UpdatedBy,
	)
	var i ReceivableSnapshot
	err := row.Scan(
		&i.ID,
		&i.ReceivableID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertReceivableSnapshot = `-- name: UpsertReceivableSnapshot :one
WITH owned_receivable AS (
    SELECT r.id AS rid
    FROM receivables r
    WHERE r.id = $1 AND r.household_id = $8::uuid AND r.deleted_at IS NULL
)
INSERT INTO receivable_snapshots (
    receivable_id, year_month, amount, currency, as_of_date, description,
    created_by, updated_by
)
SELECT owned_receivable.rid, $2, $3, $4, $5, $6, $7, $7
FROM owned_receivable
ON CONFLICT (receivable_id, year_month) WHERE deleted_at IS NULL
DO UPDATE SET
    amount      = EXCLUDED.amount,
    currency    = EXCLUDED.currency,
    as_of_date  = EXCLUDED.as_of_date,
    description = EXCLUDED.description,
    updated_by  = EXCLUDED.updated_by,
    updated_at  = now()
RETURNING id, receivable_id, year_month, amount, currency, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
`

type UpsertReceivableSnapshotParams struct {
	ID          uuid.UUID       `json:"id"`
	YearMonth   time.Time       `json:"year_month"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	AsOfDate    *time.Time      `json:"as_of_date"`
	Description *string         `json:"description"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	HouseholdID uuid.UUID       `json:"household_id"`
}

// UpsertReceivableSnapshot inserts a snapshot or, when one already exists for
// the (receivable_id, year_month) pair, overwrites it (last-write-wins) — the
// importer needs idempotent re-runs of a multi-year backfill. ON CONFLICT
// targets the partial unique index, so its predicate (deleted_at IS NULL) is
// repeated. created_by is only set on insert; updated_by always.
func (q *Queries) UpsertReceivableSnapshot(ctx context.Context, arg UpsertReceivableSnapshotParams) (ReceivableSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertReceivableSnapshot,
		arg.ID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.AsOfDate,
		arg.Description,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i ReceivableSnapshot
	err := row.Scan(
		&i.ID,
		&i.ReceivableID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
