// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createLocalUser = `-- name: CreateLocalUser :one
INSERT INTO users (
    household_id, display_name, email, locale, time_zone, picture_url, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $7
)
RETURNING id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at, nickname, picture_url, theme, carryover_date_mode
`

type CreateLocalUserParams struct {
	HouseholdID uuid.UUID  `json:"household_id"`
	DisplayName string     `json:"display_name"`
	Email       string     `json:"email"`
	Locale      string     `json:"locale"`
	TimeZone    string     `json:"time_zone"`
	PictureUrl  *string    `json:"picture_url"`
	CreatedBy   *uuid.UUID `json:"created_by"`
}

// The local-password create path (ADR-0039): no google_sub (left NULL — a
// local-only User is identified by email and proves it with a local_credentials
// row). Mirrors CreateUser otherwise. The credential row is written separately
// (UpsertLocalCredential) so the secret never rides the identity insert.
func (q *Queries) CreateLocalUser(ctx context.Context, arg CreateLocalUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createLocalUser,
		arg.HouseholdID,
		arg.DisplayName,
		arg.Email,
		arg.Locale,
		arg.TimeZone,
		arg.PictureUrl,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Email,
		&i.GoogleSub,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Nickname,
		&i.PictureUrl,
		&i.Theme,
		&i.CarryoverDateMode,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    household_id, display_name, email, google_sub, locale, time_zone, picture_url, created_by, updated_by
) VALUES (
    $1, $2, $3, $4::text,
    $5, $6, $7, $8, $8
)
RETURNING id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at, nickname, picture_url, theme, carryover_date_mode
`

type CreateUserParams struct {
	HouseholdID uuid.UUID  `json:"household_id"`
	DisplayName string     `json:"display_name"`
	Email       string     `json:"email"`
	GoogleSub   string     `json:"google_sub"`
	Locale      string     `json:"locale"`
	TimeZone    string     `json:"time_zone"`
	PictureUrl  *string    `json:"picture_url"`
	CreatedBy   *uuid.UUID `json:"created_by"`
}

// The Google-identity create path: google_sub is the verified subject, always
// present. The ::text cast keeps the param a plain (non-null) string so the many
// existing callers are unaffected by google_sub going nullable (ADR-0039); the
// local-only path uses CreateLocalUser, which leaves google_sub NULL.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.HouseholdID,
		arg.DisplayName,
		arg.Email,
		arg.GoogleSub,
		arg.Locale,
		arg.TimeZone,
		arg.PictureUrl,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Email,
		&i.GoogleSub,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Nickname,
		&i.PictureUrl,
		&i.Theme,
		&i.CarryoverDateMode,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at, nickname, picture_url, theme, carryover_date_mode
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

// Email is the human-facing handle and (since ADR-0039) the lookup key for local
// password login. Soft-delete-aware and unique (users_email_idx), so it returns
// at most one live row. Callers must treat a miss as a generic auth failure —
// never leak whether the email exists (no user enumeration on login).
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Email,
		&i.GoogleSub,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Nickname,
		&i.PictureUrl,
		&i.Theme,
		&i.CarryoverDateMode,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at, nickname, picture_url, theme, carryover_date_mode
FROM users
WHERE google_sub = $1::text AND deleted_at IS NULL
`

// The ::text cast keeps the lookup parameter a plain (non-null) string even
// though google_sub is nullable since ADR-0039 — callers always have a concrete
// subject to look up, never NULL, and this avoids a *string param rippling
// through every caller. A NULL column value simply never equals the arg.
func (q *Queries) GetUserByGoogleSub(ctx context.Context, dollar_1 string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, dollar_1)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Email,
		&i.GoogleSub,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Nickname,
		&i.PictureUrl,
		&i.Theme,
		&i.CarryoverDateMode,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at, nickname, picture_url, theme, carryover_date_mode
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Email,
		&i.GoogleSub,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Nickname,
		&i.PictureUrl,
		&i.Theme,
		&i.CarryoverDateMode,
	)
	return i, err
}

const listUsersByHousehold = `-- name: ListUsersByHousehold :many
SELECT id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at, nickname, picture_url, theme, carryover_date_mode
FROM users
WHERE household_id = $1
  AND deleted_at IS NULL
ORDER BY display_name ASC
`

func (q *Queries) ListUsersByHousehold(ctx context.Context, householdID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.DisplayName,
			&i.Email,
			&i.GoogleSub,
			&i.Locale,
			&i.TimeZone,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Nickname,
			&i.PictureUrl,
			&i.Theme,
			&i.CarryoverDateMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPicture = `-- name: SetUserPicture :one
UPDATE users
SET picture_url = $2,
    updated_at  = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at, nickname, picture_url, theme, carryover_date_mode
`

type SetUserPictureParams struct {
	ID         uuid.UUID `json:"id"`
	PictureUrl *string   `json:"picture_url"`
}

// Refresh the Google-sourced profile picture on login. This is a system sync
// from the OIDC claims, not a user edit, so updated_by is deliberately left
// alone (it stays the last human editor). The caller only invokes this when the
// incoming picture differs from the stored one, to avoid touching the row on
// every login. NULL clears it (Google omitted one).
func (q *Queries) SetUserPicture(ctx context.Context, arg SetUserPictureParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPicture, arg.ID, arg.PictureUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Email,
		&i.GoogleSub,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Nickname,
		&i.PictureUrl,
		&i.Theme,
		&i.CarryoverDateMode,
	)
	return i, err
}

const updateUserCarryoverDateMode = `-- name: UpdateUserCarryoverDateMode :one
UPDATE users
SET carryover_date_mode = $2,
    updated_by          = $1,
    updated_at          = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at, nickname, picture_url, theme, carryover_date_mode
`

type UpdateUserCarryoverDateModeParams struct {
	UpdatedBy         *uuid.UUID `json:"updated_by"`
	CarryoverDateMode string     `json:"carryover_date_mode"`
}

// Self-attributed: the user sets how the carryover dialog seeds its as-of date
// (issue #105). The DB CHECK (migration 00002) enforces the allowed set; the
// handler additionally validates before issuing this query so the client gets a
// 400 rather than a 500 on a bad value.
func (q *Queries) UpdateUserCarryoverDateMode(ctx context.Context, arg UpdateUserCarryoverDateModeParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserCarryoverDateMode, arg.UpdatedBy, arg.CarryoverDateMode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Email,
		&i.GoogleSub,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Nickname,
		&i.PictureUrl,
		&i.Theme,
		&i.CarryoverDateMode,
	)
	return i, err
}

const updateUserLocale = `-- name: UpdateUserLocale :one
UPDATE users
SET locale     = $2,
    updated_by = $1,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at, nickname, picture_url, theme, carryover_date_mode
`

type UpdateUserLocaleParams struct {
	UpdatedBy *uuid.UUID `json:"updated_by"`
	Locale    string     `json:"locale"`
}

// Self-attributed UI-language change. The DB CHECK (migration 00020) enforces
// the allowed BCP47 set; the handler additionally validates before issuing
// this query so the client gets a 400 rather than a 500 on a bad value.
func (q *Queries) UpdateUserLocale(ctx context.Context, arg UpdateUserLocaleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLocale, arg.UpdatedBy, arg.Locale)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Email,
		&i.GoogleSub,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Nickname,
		&i.PictureUrl,
		&i.Theme,
		&i.CarryoverDateMode,
	)
	return i, err
}

const updateUserNickname = `-- name: UpdateUserNickname :one
UPDATE users
SET nickname   = $2,
    updated_by = $1,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at, nickname, picture_url, theme, carryover_date_mode
`

type UpdateUserNicknameParams struct {
	UpdatedBy *uuid.UUID `json:"updated_by"`
	Nickname  *string    `json:"nickname"`
}

// Self-attributed: a user updates only their own nickname (id = updated_by).
// nickname NULL clears it; the length CHECK guards 1..32 chars when set.
func (q *Queries) UpdateUserNickname(ctx context.Context, arg UpdateUserNicknameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserNickname, arg.UpdatedBy, arg.Nickname)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Email,
		&i.GoogleSub,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Nickname,
		&i.PictureUrl,
		&i.Theme,
		&i.CarryoverDateMode,
	)
	return i, err
}

const updateUserTheme = `-- name: UpdateUserTheme :one
UPDATE users
SET theme      = $2,
    updated_by = $1,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at, nickname, picture_url, theme, carryover_date_mode
`

type UpdateUserThemeParams struct {
	UpdatedBy *uuid.UUID `json:"updated_by"`
	Theme     string     `json:"theme"`
}

// Self-attributed UI-theme change (light/dark). The DB CHECK (migration 00024)
// enforces the allowed set; the handler additionally validates before issuing
// this query so the client gets a 400 rather than a 500 on a bad value.
func (q *Queries) UpdateUserTheme(ctx context.Context, arg UpdateUserThemeParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTheme, arg.UpdatedBy, arg.Theme)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Email,
		&i.GoogleSub,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Nickname,
		&i.PictureUrl,
		&i.Theme,
		&i.CarryoverDateMode,
	)
	return i, err
}
